### ISSUE TITLE
Add yourself to the contributors, if you want :)

### ISSUE THREAD

**Issue by tdegrunt** [tdegrunt/jsonschema#103]
You have been doing so much lately for this library, seems only fair.
I could do it, but have no idea how you want to be mentioned and whether you want to.

**Comment by Acubed** [comment]
Oh sure, I guess :)
"Austin Wright" is sufficient, which are the relevant files do you think?

**Comment by tdegrunt** [comment]
package.json takes a contributors key (array) and in README.md we can just make a section contributors.
