### ISSUE TITLE
Re: Custom error messages

### ISSUE THREAD

**Issue by mershal** [tdegrunt/jsonschema#106]
This library was the best I've ever used, but unfortunately I had to stop using it because it didn't support custom error messages. It would be nice if such a critical feature existed. I'm pretty sure it can help lots of people.

[revalidator] (https://github.com/flatiron/revalidator) has this feature but it lacks some awesome draft 4 support that jsonschema has

Thanks!

**Comment by Acubed** [comment]
@mershal does issue #50 describe your problem? If so you can close this, and take a look at the progress being described over there. Thanks!

**Comment by mershal** [comment]
Yes! This is super awesome! Thanks a lot!
