### ISSUE TITLE
Json schma fails to validate perfectly good URL

### ISSUE THREAD

**Issue by steowens** [tdegrunt/jsonschema#109]
The following is an error report my service generates using the validation result provided by jsonschema but re-organized for better readability.  The validation fails on a url that is well formed because the schema validator thinks the URL is not well formed.

```
{
  "type": "INPUT_VALIDATION_ERROR",
  "details": {
    "valid": false,
    "errors": [
      {
        "property": "instance.featuresProvided[0].onboardingLink",
        "message": "does not conform to the 'url' format",
        "schema": {
          "type": "string",
          "description": "The link for onboarding onto this feature.",
          "format": "url"
        },
        "instance": "http://getStartedWithAce.com/go",
        "stack": "instance.featuresProvided[0].onboardingLink does not conform to the 'url' format"
      }
    ],
    "objectValidated": {
      "name": "ACE",
      "type": "SERVICE",
      "featuresProvided": [
        {
          "name": "RIGHTS_MANAGEMETN",
          "description": "Manage permissions and secured entities",
          "onboardingLink": "http://getStartedWithAce.com/go",
          "subscriptionMetadataSchema": {
            "type": "string"
          }
        }
      ],
      "revision": 0
    },
    "schemaUsed": {
      "id": "Entity",
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "description": "Unique system identifier for the entity.  This will be assigned by the system and need not be provided by the client for new entities."
        },
        "revision": {
          "type": "integer",
          "description": "Assigned by the system to track revisions, and coordinate predictable updates.  This will be assigned (and maintained) by the system and need not be provided by the client for new entities."
        },
        "name": {
          "type": "string",
          "description": "A name that IS unique that may not be so friendly.",
          "required": true
        },
        "type": {
          "type": "string",
          "enum": [
            "GUEST",
            "CAST_MEMBER",
            "APPLICATION",
            "SERVICE",
            "DEVICE"
          ],
          "required": true
        },
        "featuresProvided": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Unique identifier with respect to the Provider Entity for the feature."
              },
              "description": {
                "type": "string",
                "description": "Describes what the feature is or does."
              },
              "onboardingLink": {
                "type": "string",
                "description": "The link for onboarding onto this feature.",
                "format": "url"
              },
              "subscriptionMetadataSchema": {
                "type": "any"
              }
            }
          }
        }
      },
      "example": {
        "_id": "54ed3472cd3a24dc57679a2e",
        "revision": 0,
        "type": "SERVICE",
        "name": "ACE",
        "contactEmail": "DTSS.Disney.Web.Services@disney.com",
        "description": "Fine grained dynamic, self service authorization provider.",
        "featuresProvided": [
          {
            "name": "rights-management",
            "description": "Register items to secure and assign permissions to manage those items to users, groups and based on other criteria.",
            "onboardingLink": "https://beta.dws.cloud.corp.dig.com/",
            "subscriptionMetadataSchema": null
          }
        ]
      }
    }
  }
}
```

**Comment by Acubed** [comment]
You're probably looking for the `uri` format, JSON Schema doesn't provide for a "url" format. I'll take a look at why it seems there is one, though.

**Comment by tdegrunt** [comment]
Can you provide me with the original schema and object you validated?

**Comment by Acubed** [comment]
it should be right there in the "errors" list:

{
        "schema": {
          "type": "string",
          "description": "The link for onboarding onto this feature.",
          "format": "url"
        }
        "instance": "http://getStartedWithAce.com/go"
}

It looks like validating against a format that doesn't exist always fails.

**Comment by tdegrunt** [comment]
Ah missed that, I'm on mobile. It's the url vs uri thing alright. We should probably error out on an invalid format then ... :)

**Comment by tdegrunt** [comment]
Reading here: http://json-schema.org/latest/json-schema-validation.html#anchor105

    "The value of this keyword is called a format attribute. It MUST be a string. A format attribute can generally only validate a given set of instance types. If the type of the instance to validate is not in this set, validation for this format attribute and instance SHOULD succeed."

Should we just say it's valid? 

I have code ready to throw an SchemaError if an invalid format is passed, including test.

**Comment by Acubed** [comment]
Yeah, it should probably normally succeed, same as unknown properties.

I'll make a PR for this as a test to the official test suite over the weekend, to formally run this behavior by other implementations.

**Comment by tdegrunt** [comment]
I think I have this fixed with the following (in develop branch):
https://github.com/tdegrunt/jsonschema/commit/14a8429e43349005e8f0781a8b184718d9afca15

**Comment by acusti** [comment]
Seems like @tdegrunt’s fix for this has been orphaned in develop. Regarding whether unrecognized formats should fail or pass, I believe it is correct behavior that it passes, though I couldn’t find a test for it in the [suite](https://github.com/json-schema/JSON-Schema-Test-Suite/blob/develop/tests/draft4/optional/format.json). Other validators (like [tv4](https://github.com/geraintluff/tv4/blob/master/source/validate.js#L319)) take that approach, so I’m guessing that is correct.

I think a PR from develop into master would do the trick.
