### ISSUE TITLE
Json scheam validator fails to honor REGEX

### ISSUE THREAD

**Issue by steowens** [tdegrunt/jsonschema#112]
Json schema validator fails on patterns such as this:
```
"pattern": "^[A-Za-z0-9-_][A-Za-z0-9-_ ]*[A-Za-z0-9-_]$"
```

Per the regex specification this pattern should only match if the leading and trailing characters are non blank and in the character set [A-Za-z0-9-_ ]*, and allow any string with a leading and trailing non blank character that has middle characters i the character set: [A-Za-z0-9-_ ]*

Yet the error message that gets passed back when passing in a string such as "Hobo$" says that the value must be in the character set [A-Za-z0-9-_ ], and further more it will accept "Hobos " as well as " Hobos".

This is not expected behavior.

**Comment by Acubed** [comment]
Can you provide a regression? I'm not seeing this behavior:

```javascript
var s = {"pattern": "^[A-Za-z0-9-_][A-Za-z0-9-_ ]*[A-Za-z0-9-_]$"};
j.validate('Hobos', s).valid; // true
j.validate(' Hobos', s).valid; // false
j.validate('Hobos ', s).valid; // false
j.validate('Hobo$', s).valid; // false
```

**Comment by tdegrunt** [comment]
@steowens Anything? Otherwise I'll close for inactivity...

**Comment by steowens** [comment]
I guess closing it is the appropriate thing to do at this point.  I was able to craft a different Regex that meet my needs.  I no longer have the repro steps for this.  Sorry for that.
