### ISSUE TITLE
Long time since last release..

### ISSUE THREAD

**Issue by torarvid** [tdegrunt/jsonschema#117]
Hey. Do you have any plans to do a new release soonish?

(Just asking since current master has fixed several issues, and for us npm users, a new release would be super nice)

**Comment by tdegrunt** [comment]
Hi, We've just released 1.0.1 16 days ago. Is there anything missing in there?

**Comment by torarvid** [comment]
Oh, I'm sorry.. I just saw here on the github releases page, that v1.0.0 from July, 2014 was the latest release.

I see now that on npm, 1.0.1 is actually the latest one. Thanks!

(Just curious, am I seeing something wrong on the github releases page, or is there another reason 1.0.0 is the latest one?)

**Comment by tdegrunt** [comment]
No need to be sorry! I think I messed up the release on github there, just pushed to npm. I'll get that sorted, thank you for reporting this!

**Comment by torarvid** [comment]
Well, it's there now, so I'll close the issue. Thanks for the swift response :+1:
