### ISSUE TITLE
Error: instance is not of a type(s) array

### ISSUE THREAD

**Issue by yarax** [tdegrunt/jsonschema#129]
Hello!
I use: 
```javascript
v.validate(item, schema);
// item: [{...}]
// schema { type: 'array', items: { schema: { '$ref': '#/definitions/place' } } }
```
And got an error: `Error: instance is not of a type(s) array`
As I understand the problem is that `typeof [] === 'object'` in https://github.com/tdegrunt/jsonschema/blob/master/lib/validator.js#L275

**Comment by Acubed** [comment]
I can't seem to reproduce this. Can you provide a specific regression? In particular, your code snippet contains three undefined variables, and the schema in the comment refers to another schema that isn't defined.

**Comment by yarax** [comment]
Sorry, it was my fault. That's ok!
