### ISSUE TITLE
Enum type attributes

### ISSUE THREAD

**Issue by inteloid** [tdegrunt/jsonschema#131]
Hi, it is quite common when an property can have only value from a predefined set of values, for instance: gender, country, os, etc.

If there's a support for that, tell me how to use it, but I didn't find it in docs.

**Comment by Acubed** [comment]
The vocabulary itself is standardized elsewhere: http://json-schema.org/documentation.html

There is an "enum" validator, which is an array: `{"enum":[1, "1", true]}`

**Comment by inteloid** [comment]
thanks
