### ISSUE TITLE
Restrict Additional Properties

### ISSUE THREAD

**Issue by rkaneriya** [tdegrunt/jsonschema#132]
Currently, if an instance contains additional properties beyond those specified in a schema, the instance is still considered valid. 

Is it possible to provide a way to specify in the schema whether or not additional properties should be allowed. Maybe this could just be a boolean called "additionalProperties" (like in this schema validator: http://spacetelescope.github.io/understanding-json-schema/reference/object.html). 

Thanks!

**Comment by tdegrunt** [comment]
jsonschema supports `additionalProperties` allright, have you tried that?

See:
http://json-schema.org/latest/json-schema-validation.html#anchor64

**Comment by rkaneriya** [comment]
Ahh, I must've missed that. Thanks!
