### ISSUE TITLE
Resetting errors

### ISSUE THREAD

**Issue by hagner** [tdegrunt/jsonschema#133]
As a way of building my schema (in node.js), I'm writing mocha tests including a whole bunch of negative tests to catch all edge cases. However, it doesn't seem to make any difference if I try to create new instances of validator, it seems to aggregate up errors, i.e. not clear the errors content between run. Ideally, I would like a method which "resets" the validator between runs. Is that possible? Have I missed something?

Sincerely,

Nils Hagner

**Comment by Acubed** [comment]
Can you please provide a regression to run, and show the error?

Errors aren't stored in the validator state, so I'm not sure what the issue could be.

**Comment by hagner** [comment]
Hi!

While trying to reproduce the thing in a condensed way, then I think I spotted the problem. Looks like node's require caching (combined with non-perfect code by me) messed up the results a bit. I managed to get the tests to behave the way I wanted, so false alarm on this one. Apologies.

Sincerely,

Nils


On 29/06/2015 06:18, Acubed wrote:

Can you please provide a regression to run, and show the error?

Errors aren't stored in the validator state, so I'm not sure what the issue could be.

-
