### ISSUE TITLE
Repository lacks tags

### ISSUE THREAD

**Issue by awwright** [tdegrunt/jsonschema#14]
Releases should be tagged in the Git repository, this helps developers using package management tools, and helps software depending on this repository figure out which future releases are compatible (when employing semver semantics).

I tagged all the releases through 0.2.0 in my repository with the lightweight tags, pointing to the commit where package.json was touched. These may be pulled.

**Comment by raoulus** [comment]
Hi guys,

I am noticing that there are still some missing tags in git. I am using v1.0.3 right now and I would like to check the differences to v1.1.0. @tdegrunt did you forget to create them? Can you create a tag for the current release?

Thanks!
