### ISSUE TITLE
Does not validate against an array of string when null values are present

### ISSUE THREAD

**Issue by ryandac** [tdegrunt/jsonschema#141]
For a schema of an array of strings of fixed length, when null or undefined values are entered your Json schema validator does not pick up errors.

e.g. 
 arrayOf5Strings: [ '1', , '3', '4', undefined ]
validates successfully agains schema
schema
"arrayOf5Strings": {
                    "id": "arrayOf5Strings",
                    "type": "array",
                    "items": [
                        {
                            "id": "0",
                            "type": "string"
                        },
                        {
                            "id": "1",
                            "type": "string"
                        },
                        {
                            "id": "2",
                            "type": "string"
                        },
                        {
                            "id": "3",
                            "type": "string"
                        },
                        {
                            "id": "4",
                            "type": "string"
                        }
                    ]
                }

**Comment by Acubed** [comment]
Can you post a specific regression (a short program calling jsonschema), along with expected and actual output?

Also note that `undefined` isn't valid JSON, and presence or absence of a value is handled by the "required" keyword.

**Comment by tdegrunt** [comment]
Closed due to inactivity
