### ISSUE TITLE
Do not validate date-time 

### ISSUE THREAD

**Issue by i3fox** [tdegrunt/jsonschema#142]
I have an error to validate a date-time property.
Value of datetime is "2015-09-28T10:40:00+0200".

**Comment by Acubed** [comment]
Don't forget to post a regression so we can verify what you're talking about.

It should just be a short code sample that replicates the problem that you're talking about, as well as expected and actual output.

**Comment by i3fox** [comment]
var jsonschema = require("jsonschema");
var validator = new jsonschema.Validator();
var validation = validator.validate("2015-09-28T10:40:00+0200", {'type': 'string', 'format': 'date-time'});
console.log("IsValid: " + validation.valid); 

I expected 'validation.valid' true but result is false.

**Comment by DmitryLapshov** [comment]
@i3fox 
It doesn't seem to accept 0200. Use 02:00 instead.
"2015-09-28T10:40:00+02:00" is valid

**Comment by i3fox** [comment]
I receive this time from another system. That is not under my control.

**Comment by Acubed** [comment]
Oh, yeah.

The `time-date` format requires an RFC 3339 `date-time` production, including the following:

    date-time       = full-date "T" full-time
    time-numoffset  = ("+" / "-") time-hour ":" time-minute
    time-offset     = "Z" / time-numoffset

So JSON Schema is working exactly right, you're saying you expect a date-time, and you're not getting a valid one. So I don't think there's anything we can do about this.

If you have any further suggestions please let us know, or else you can close out this issue.

**Comment by tdegrunt** [comment]
It seems the timezone is also allowed without the colon, see:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

I'm thinking to put a ? behind the colon at the end of:
https://github.com/tdegrunt/jsonschema/blob/master/lib/helpers.js#L115

What do you think?

**Comment by tdegrunt** [comment]
Weird:
`new Date().toString()`

gives no colon...

**Comment by tdegrunt** [comment]
One last thought:
http://tools.ietf.org/html/rfc3339#section-5

shows:
`time-numoffset    = ("+" / "-") time-hour [[":"] time-minute]`

So even then, the date-time given is wrong as it's giving 4 digits not two.
We could extend the regex to allow the above?

But how many different RFC 3339 are there? :)

**Comment by Acubed** [comment]
Date#toString() is defined as:

    Return an implementation-dependent String value that represents tv as a date and time in the current time zone using a convenient, human-readable form.

So it could be anything.

I can't find any way to produce a format that produces a timezone. Date#toISOString() only produces a `Z` suffix.

In any event, you can use a regex for this, since this is used for checking /outgoing/ data too, which does need to be stricter.

The `time-numoffset = ("+" / "-") time-hour [[":"] time-minute]` is the ISO8601 format, not the stricter RFC3339 format.

**Comment by i3fox** [comment]
In my case it would be interesting to also validate the ISO 8601 format.
I think another possible solution is to give the opportunity to do an override of a type (in this case 'date-time') to implement my validation.

What do you think?

**Comment by tdegrunt** [comment]
You can, but using `pattern`:
See http://json-schema.org/example2.html specifically the "The diskDevice storage type" example.

You can use one of the regexp examples here:
http://stackoverflow.com/questions/12756159/regex-and-iso8601-formated-datetime

**Comment by i3fox** [comment]
Ok, Thanks
