### ISSUE TITLE
Custom Error Messaging

### ISSUE THREAD

**Issue by aray12** [tdegrunt/jsonschema#147]
I know some people have recommended custom error messaging. Would something like the following make more sense and be easier to declare?

``` javascript
var schema = {
  "id": "/All",
  "type": "object",
  "properties": {
      "validateType1": {
         "type": {
           "value": "string",
           "errorMessage": "this is now a string and I am telling you how I like"
         }
      }  
   }  
}
```

This would definitely make internationalization easier.

**Comment by Acubed** [comment]
It needs some documentation, maybe a tutorial on how to get it working, but the returned error list contains `name` and `argument` properties, as well as the original failing schema, including the `id` property if any.

The `message` property that's returned is computed from the `name` and `argument` properties, but you can do this yourself in your preferred locale, too.

Is that helpful at all?

**Comment by lganet** [comment]
Yes, mainly for translation to other language.

**Comment by awwright** [comment]
Merging this with #212
