### ISSUE TITLE
Schemas are not available in the published npm package.  npm publish?

### ISSUE THREAD

**Issue by jsdevel** [tdegrunt/jsonschema#155]
It would be nice to have `require('jsonschema/schema/draft-04/schema.json')` available.

**Comment by Acubed** [comment]
@jsdevel v1.0.3 released, try it out and report back

**Comment by Acubed** [comment]
@jsdevel Can you confirm this fixes your problem?

(Austin Wright here btw, fancy seeing you here!)

**Comment by jsdevel** [comment]
hey!  I was wondering if it was you!  Let me check real quick...

**Comment by jsdevel** [comment]
BTW, I got https://github.com/kogosoftwarellc/express-openapi added to [swagger.io integrations page](http://swagger.io/open-source-integrations/).  It's leveraging `jsonschema` to the max.  Check it out if you have time.

**Comment by jsdevel** [comment]
That did the trick @Acubed !  Thanks!
