### ISSUE TITLE
Explain 'id' behaviour

### ISSUE THREAD

**Issue by stevage** [tdegrunt/jsonschema#156]
I've previously used JSON Editor and have not set `id` on any of my schemas. However, `jsonschema` didn't like that.

My situation is a root schema and a number of subschemas, all loaded from the same local directory.

It took a bit of fiddling around to find a combination `jsonschema` would accept:
- `id`: `/rootschema.json` for the root
- `id`: `subschema.json` for the others.

A bit of guidance in the README would be helpful for first time users.

**Comment by Acubed** [comment]
You shouldn't need to do anything too special. Can you give some more specific examples on what you're doing?

Can you elaborate on how the behavior defers from other validators, if possible?

Could you provide something you expected to work that didn't?

Now, "id" works best with a (full, absolute) URI. URI references are resolved relative to that one, so for other places in the document you can just use `"file.json"` and it'll resolve to the same file path. If you're loading these files from a remote or local source, you probably also want to provide the URI, e.g. `file:///var/lib/foo/schema/base.json`

**Comment by stevage** [comment]
Ok, here's my complete validator code:

```
var v = new (require('jsonschema').Validator)();
var ValidatorResult = require('jsonschema').ValidatorResult;
var fs = require('fs');
var path = '../autoDataSourceEditor';
var rootSchema;
function validate() {
    console.log('Commencing validation.');
    var filenames = ['../nm-clean/wwwroot/init/nm.json'];
    filenames.forEach(function(filename) {
        fs.readFile(filename, 'utf8', function(err, data) {
            data = JSON.parse(data);
            var result  = v.validate(data, rootSchema);
            if (result.errors.length) {
                console.error(filename + ' FAILED validation');
                result.errors.forEach(function(error) {
                    if (error.instance.name && error.instance.type) {
                        console.error(error.instance.name + '" (' + error.instance.type + ') ' + error.message);
                    } else {
                      console.error(error.stack);
                      console.error('where ' + error.property + ' is: ');
                      console.error(JSON.stringify(error.instance, undefined, 2));
                    }
                });
                //console.log(JSON.stringify(result.errors, undefined, 2));
            } else {
                console.log(filename + ' passed validation.');
            }
        });
    });
}

function loadNextSchema(filename) {
    fs.readFile(path + '/' + filename, 'utf8', function(err, data) {
        var schema = JSON.parse(data);
        if (!rootSchema) {
            rootSchema = schema;
            schema.id = '/' + filename;
        } else {
            schema.id = filename;
        }
        v.addSchema(schema);
        //console.log('Schema added ok.');
        var next = v.unresolvedRefs.shift();
        if (next) {
            loadNextSchema(next);
        } else {
            validate();
        }

        //console.log(v.validate({catalog: 'blah'}, schema));
    });
}
console.log('Loading schemas.');
loadNextSchema('Catalog.json');
```

>Could you provide something you expected to work that didn't?

I did not expect to have to manually provide an `id`. However, removing the two `schema.id = ` lines results in this error:

```
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:110:11)
```

>Can you elaborate on how the behavior defers from other validators, if possible?

Ok, here's my editor, built on JSONeditor: http://terria.io/auto-datasourceeditor/

The schema contains no `id` elements: http://terria.io/auto-datasourceeditor/Catalog.json

I think I now understand why the schemas have to have `id`s (because we're feeding JSON into `addSchema` and it has no idea what file the JSON came from), but that wasn't obvious when I first started. (Again, to be clear, I'm not asking for support, I'm making a suggestion about documentation.)

**Comment by ebickle** [comment]
This is a bug. The "id" keyword is optional.

http://json-schema.org/latest/json-schema-core.html#rfc.section.8.2

"If present, the value for this keyword..."

**Comment by awwright** [comment]
I can't reproduce this, without a stack trace or example schema.

My apologies for not getting to this sooner.

**Comment by awwright** [comment]
Some of how "id" is used has changed over the past few releases. If anyone has any problems still, please open a new issue and I'll take another look.

I will note, you should use a _full_, absolute URI like so:

```
{ "id": "http://example.com/foo.schema.json" }
```

This will probably fix most problems that people have with "id".
