### ISSUE TITLE
Optional properties with format validation

### ISSUE THREAD

**Issue by hbj** [tdegrunt/jsonschema#167]
Hi,

how can we define an optional property with format validation?

If I use the following:

```
"email": {
  "type": "string",
  "format": "email"
},
```

Validating an empty string for `email` would result in a format validation error. Shouldn't the validator only take non empty strings into account?

**Comment by tdegrunt** [comment]
Hi,

This is what the spec says:
http://json-schema.org/latest/json-schema-validation.html#anchor33

If you want to optionally check if it's an email, you would have to write a regexp yourself and allow for an empty string as well.

Let me know if this answers your question.

Cheers!

**Comment by Acubed** [comment]
@hbj This is a good question for the JSON Schema mailing list since it's about writing JSON Schemas; but, you're probably looking for the "anyOf" keyword, something like:

```javascript
"email": {
  "anyOf": [
    {"type":"string", "format":"email"},
    {"type":"string", "enum":[""]}
}
```

Alternatively, this might work if you use `null` instead:

```javascript
"email": {
  "type": ["string", "null"],
  "format": "email"
}
```

For many properties (format included, I believe), instances will be ignored if the instance being compared isn't of the type expected by the keyword (like here, providing something besides a string to the "email" formatter).

**Comment by tdegrunt** [comment]
@hbj Any update, can we close this issue?

**Comment by hbj** [comment]
@tdegrunt sorry for the delay.

The spec says:

> A string instance is considered valid if the regular expression matches the instance successfully.

A regular expression can allow for an empty string, but I don't know whether this is considered 'correct'. IMHO an instance should only be validated if it's not empty, to make sure that, when it has a value, this value has the correct format. Whether it is allowed to be empty or not, should be the role of the `required` validator.

The solution of @Acubed looks good, but it feels like a workaround to me (but might be the way to go).

@tdegrunt if you think this can't be fixed without breaking the spec, then this ticket can be closed. Thanks.

**Comment by awwright** [comment]
This appears to have the correct behavior:

```javascript
validate(null, {type:'string', format:'email'}).valid
// false

validate("", {type:'string', format:'email'}).valid
// false

validate("mailbox@example.com", {type:'string', format:'email'}).valid
// true
```
This isn't a bug with how the JSON Schema spec is implemented so I'm going to close this.

My two suggestions for doing this are:

1. Have your application read an empty value as `undefined` or `null`.

2. Use the `"oneOf"` keyword to say e.g. "permit an empty value, OR a string with a valid email address"
