### ISSUE TITLE
Error in the typescript definitions with noImplictAny

### ISSUE THREAD

**Issue by Bnaya** [tdegrunt/jsonschema#168]
```
jsonschema/lib/index.d.ts(14,5): error TS7010: 'validate', which lacks return-type annotation, implicitly has an 'any' return type.
```

I hope i will get to it and make a PR

**Comment by Bnaya** [comment]
#165

**Comment by tdegrunt** [comment]
I have zero experience in Typescript, but seen the added value. It's hard for me to maintain this code, so if you can make a PR for this, I'll be happy to merge. Cheers.

**Comment by Bnaya** [comment]
pr: #171

**Comment by mizunashi-mana** [comment]
Suggest:
TypeScript usually manage definitions on http://definitelytyped.org.

We should move typescript definitions to definitely typed repository from this repository.

## Notes

Many supporters fix all definitions.  If typescript is updated and there are some errors, supporter fixes errors.

**Comment by Bnaya** [comment]
@mizunashi-mana
There's a lot of benefits from bundling d.ts files with the module
Also the typings repo is the more current way to handle definitions 
https://github.com/typings/typings
as the tsd tool is deprecated 
https://github.com/DefinitelyTyped/tsd/issues/269

**Comment by mizunashi-mana** [comment]
@Bnaya 
`tsd` was deprecated, but https://github.com/DefinitelyTyped/DefinitelyTyped is not.

If this library was written by TypeScript, bundling type definitions file with this library would have been good idea for me.
However, this library is **a JavaScript library**.

I'm a TypeScript user.  But there are some supersets of JavaScript and their users now (e.g. facebook flow/Haxe).
If this library has some supports of TypeScript, I think we should add some other superset supports.
However, I think this is bad ideas and this library has no obligation to watch latest TypeScript changes.

TypeScript can declare types of JavaScript library without bundling codes.  So, DefinitelyTyped has been hosted type files of **JavaScript libraries**. (Actually, old definition manager, `tsd` is not good tool...  So, in the many cases, libraries written by TypeScript was added on DefinitelyTyped...)

If typescript is updated, DefinitelyTyped supporters check **all type files** and fix.  And, NuGet supporting is available.  New definition manager also support DefinitelyTyped!  Perhaps, there will have been many support of DefinitelyTyped for TypeScript coding.

I think this library should support only JavaScript and TypeScript definition file move to DefinitelyTyped.  Actually, `index.d.ts` seems to have some problems for me (there is not type tests, and wrong type signatures).  What about?

**Comment by mizunashi-mana** [comment]
Ah, sorry...

https://github.com/typings/registry was available.
This registry is better than DefinitelyTyped for me.  However, it seems to be not stable.
Maybe, big changes come.
I think most of TypeScripters use DefinitelyTyped yet.

If we use typings registry:
 1. create type repository, `typed-npm-jsonschema`
 2. write README.md/index.d.ts/test.ts like https://github.com/typed-typings/npm-yargs
 3. Request https://github.com/typings/registry to regist
