### ISSUE TITLE
validation of string types with null instance

### ISSUE THREAD

**Issue by cguedes** [tdegrunt/jsonschema#170]
The [current code](https://github.com/tdegrunt/jsonschema/blob/master/lib/validator.js#L291) to validate strings is not conforming the [JSON Schema Validation spec](http://json-schema.org/latest/json-schema-validation.html#anchor4).

> 3.1 Validation of string instances
> ----
> It should be noted that the nul character (\x00) is valid in a JSON string. An instance to validate may contain a string value with this character, regardless of the ability of the underlying programming language to deal with such data.

~~~javascript
types.string = function testString (instance) {
  return typeof instance == 'string';
};
~~~

We should update this code to

~~~javascript
types.string = function testString (instance) {
  return instance === null || typeof instance == 'string';
};
~~~

**Comment by tdegrunt** [comment]
Are you sure it's just `\x00`, not `"\x00"`? 
From that text I'm assuming it's the latter, thereof the test is still correct?

\x00 in itself is invalid JSON:
{"test": \x00} 

See http://jsonlint.com

**Comment by cguedes** [comment]
You are right. The spec is speaking about that character inside of a string.
I've checked the JSON Spec (http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) and strings are:

> A string is a sequence of Unicode code points wrapped with quotation marks

**Comment by tdegrunt** [comment]
No problem, thanks for checking!
