### ISSUE TITLE
options.allowUnknownInstanceAttributes

### ISSUE THREAD

**Issue by lukewilde** [tdegrunt/jsonschema#173]
Howdy,

I'm working on a project where I need to show validation errors if the model has properties which are not defined in the schema.

I got excited when I saw `options.allowUnknownAttributes`, but this doesn't appear to validate extra properties found on the model.

I can't see a way of making this check without manually checking the instance's properties against those in the schema and then pegging the validation issues onto the regular validation result.

It might be nice to have `options.allowUnknownInstanceAttributes` to enable this check to be made by the `Validator` internally?

I'd like to hear your thoughts. Thanks in advance.

**Comment by nopbyte** [comment]
Hello,
I am having the same issue. In short, I would like to see that the attribute "some" is not expected in the following example. Is there any way to do this with this jsonschema module?
```
  var Validator = require('jsonschema').Validator;
  var v = new Validator();
  // Person
  var schema = {
    "id": "/SimplePerson",
    "type": "object",
    "properties": {
      "name": {"type": "string"},
      "votes": {"type": "integer", "minimum": 1}
    }
  };
  var p = {
    "name": "Barack Obama",
    "votes": 1,
    "some":1
  };
  console.log(v.validate(p, schema));
  //here I would like to see that an unexpected json attribute is in p.
```
Thanks,

**Comment by carlnordenfelt** [comment]
Sounds like you are looking for `additionalProperties: false` which is part of the [JSON Schema Spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.18)

Basically:

`
var schema = {
    "id": "/SimplePerson",
    "type": "object",
   "additionalProperties": false,
    "properties": {
      "name": {"type": "string"},
      "votes": {"type": "integer", "minimum": 1}
    }
  };
`
