### ISSUE TITLE
If schema is split into multiple files then getting  Uncaught SchemaError: no such schema error

### ISSUE THREAD

**Issue by dilipkumar2k6** [tdegrunt/jsonschema#175]
I am using jsonschema npm module for json schema validation. Recently I was suppose to split my shchema into multiple files however I realized that it didn't work. Same schema works validating using http://www.jsonschemavalidator.net/ however not working using this npm module. Following are more details.

JSON Schema: 
```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
      "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }

  },
  "type": "object",
  "properties": {
    "billing_address": { "$ref": "https://run.plunker.co/preview/ciodd9uuv00093j5h7ttcm8qu/lib/definition.json#/definitions/address" },
    "shipping_address": { "$ref": "https://run.plunker.co/preview/ciodd9uuv00093j5h7ttcm8qu/lib/definition.json#/definitions/address" }
  }
}
```

json data:
```javascript
{
  "shipping_address": {
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC"
  },
  "billing_address": {
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC"
  }
}
```

I am getting following error:
 Uncaught SchemaError: no such schema https://run.plunker.co/preview/ciodd9uuv00093j5h7ttcm8qu/lib/definition.json#/definitions/address

Does jsonschema support schema definition in other file?

**Comment by awwright** [comment]
This depends on how you're importing the schemas. Can you provide a code sample, and expected and actual output of the program?

**Comment by dilipkumar2k6** [comment]
Following is the code I am using.

```
const validateAgainstSchema = (collectionName, document)=> {
  let isValidSchema = false;
  //read schema
  const schema      = require("./schema.json");
  const validator   = new Validator();
  //validate data against schema
  const result = validator.validate(document, schema);
  if (result.errors.length === 0) {
    isValidSchema = true;
  } else {
    //print error
    console.log("Error in validation " + JSON.stringify(result.errors));
  }
  console.log(`validateAgainstSchema for collection ${collectionName} and status is ${isValidSchema}`);
  return isValidSchema;
};
```

**Comment by dilipkumar2k6** [comment]
Seems like I need a loader to load the json schema file having reference of other json schema file.

**Comment by nbering** [comment]
Where are you handling the extra files?

**Comment by nbering** [comment]
I should probably add to my question above. There are example use cases where there are multiple schema "objects", that are loaded separately into Validator before the final call to `validate()`. They don't reference by URL, though. They just use an ID of sorts, but the reference schema object is already in memory.

I do remember seeing something in the docs about implementing a loader to handle fetching portions of the schema asynchronously by HTTP, but yes, that is more complicated and prone to error if there are network problems or other server availability issues.

**Comment by awwright** [comment]
@dilipkumar2k6 Take a look at the "Dereferencing schemas" section of the README. You need to tell JSON Schema how to dereference an external schema reference.

And don't forget to provide the expected and actual output of your program that you provided!

**Comment by tdegrunt** [comment]
Any update on this?

**Comment by dilipkumar2k6** [comment]
Didn't get time to exlpore referencing schema. Will try to do next week. Will post details on finding

**Comment by csharbel** [comment]
Hi

I tried adding referenced schemas but ran into the same issue. After some debugging, i found that the reference is perfectly getting added to the schemas collection but still it not able to pick it up. To me it looks like an issue in creating the context at line 141 or so - 
new SchemaContext(schema, options, propertyName, base, Object.create(this.schemas). 

I think the first parameter to Object create is the proto object and so the attributes in this.schemas does not get copied.

Maybe we should do a 
Object.create(null, this.schemas)

or even 

Object.assign({}, this.schemas).

Would be more than happy if this minor fix can be made.

Thanks
Sharbel

**Comment by awwright** [comment]
This seems to be a problem with how the schemas are imported, so I'm going to close this out. If there's any problems, don't hesitate to open a new issue. Please include a code sample with expected and actual output.
