### ISSUE TITLE
Enum validation incorrectly thinks an array is not an array

### ISSUE THREAD

**Issue by mauritslamers** [tdegrunt/jsonschema#179]
In a project I am writing, most of the code runs in a virtual machine under node. From this virtual machine I am trying to validate json schemas, created inside this virtual machine.
This causes the code at https://github.com/tdegrunt/jsonschema/blob/master/lib/attribute.js#L739 to incorrectly determine that the array I put in the schema is not an instance of Array. 

See here for the background on this issue: http://web.mit.edu/jwalden/www/isArray.html

I would propose to use 

```
Array.isArray(schema['enum'])
```

instead of the current: 

```
schema['enum'] instanceof Array
```

Array.isArray is part of ES5 which is supported long enough now, that I think that it should not cause any issues. According to MDN Array.isArray was first supported in Chrome 5, which corresponds with V8 engine v2.1, which corresponds to NodeJS v0.1.30.

**Comment by tdegrunt** [comment]
To be sure: #178 is related to this right?

I've just updated this in master as I agree Array.isArray is a better solution, besides we were already using it in the codebase.

Can you check how master works for you and let me know?

**Comment by mauritslamers** [comment]
I discovered these issues at the same time, but I think they are separate issues. This issue is about using Array.isArray(), the other about the fact that doing a validation throws an error even though the validator has been explicitly configured not to throw.

**Comment by awwright** [comment]
The library does not use `instanceof Array` anymore so I'm going to close this out.
