### ISSUE TITLE
How to specify require for at least one of two elements?

### ISSUE THREAD

**Issue by paltanmoy** [tdegrunt/jsonschema#180]
My Schema has two array elements (recurring_schedule and specific_date) and I want to have at least one of them (both can also exist) in the schema. How could I achieve this ? Is there some way to require elements conditionally so that at least one element always exist in the schema? 
```
{
	"name": "schedule1",
	"recurring_schedule": [{
		"start_date": "2025-06-19",
		"start_time": "00:00",
		"end_date": "2015-06-19",
		"end_time": "23:59"
	}],
	"specific_date": [{
		"start_date": "2025-06-19",
		"start_time": "00:00",
		"end_date": "2015-06-19",
		"end_time": "23:59"
	}]
}
```

**Comment by nbering** [comment]
I think you can manage to do that if you have the object you're validating in an array, and then define multiple types that objects in the array can be. If you have no control over the structure of the data, I would do multiple validation passes and make sure at least one passes, or just add an extra layer of validation logic for the complex rules. Complex dependencies like that aren't usually in the realm of "Schema" validation so much as application logic, but you can work around it a bit.

**Comment by awwright** [comment]
Look for the `anyOf` keyword. You can do something like:

```
anyOf: [ {required:["recurring_schedule"]}, {required:["specific_date"]} ]
```

Aside, it doesn't usually make much sense to split apart the day from the time. Combine it into a single `date` field: `start_date: "2015-06-19T00:00"`. ISO8601 and its subset RFC3339 provide ways to define durations, recurring dates, and timestamps.

**Comment by paltanmoy** [comment]
Thanks @awwright
