### ISSUE TITLE
Validate object or array of objects

### ISSUE THREAD

**Issue by vladotesanovic** [tdegrunt/jsonschema#182]
Is it possible to do something like:

```
         const schema = {
            "type": ["object", "array"],
            "properties": {
                "key": {
                    "type": "string",
                    "required": true
                },
                "value": {
                    "type": "string",
                    "required": true
                }
            }
        };
        const objectValidation = v.validate({key: "Name", value: "A10"}, schema);
        const arrayValidation = v.validate([{key: "Name", value: "A10"}], schema);
````

To validate object or array of objects with same type?

**Comment by skellertor** [comment]
Was there any resolution to this?  I want to pass the `validate` function an array of objects, and validate the objects in that array.  Is there a way to do this? Thanks!

**Comment by sagarch88** [comment]
Any update on this? Even I am facing the same issue. @tdegrunt

**Comment by sagarch88** [comment]
I have figured out the solution.

For those wondering how to use:

`{
    "id": "\partner_detail",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            // Individual properties here.
        }
    }
}`

`items` is the key, which was needed.
