### ISSUE TITLE
Schema typescript definition is missing "$ref" 

### ISSUE THREAD

**Issue by tolbahadi** [tdegrunt/jsonschema#194]
If I define a schema with `$ref` attribute, I get a typescript error saying `$ref` is not a known attribute. I think `Schema` definition is missing `$ref: string;`

**Comment by wvanvugt-speedline** [comment]
I ran into this issue too

**Comment by jphilipstevens** [comment]
any update on this? Its getting me as well

**Comment by awwright** [comment]
I'll have to look into how to add `$ref` since it's not really a JSON Schema keyword as such, but I suppose we could add it as one since it's (as of draft-05) only supposed to be found where a schema is expected.

**Comment by awwright** [comment]
It appears the TypeScript index.d.ts file now includes a "$ref" property. I'll close this out, but please open a new issue if there's anything missing from the TypeScript definitions.
