### ISSUE TITLE
cross-frame json validation (instanceOf is problematic)

### ISSUE THREAD

**Issue by gregglind** [tdegrunt/jsonschema#199]
When using `jsonschema` cross-frame, problems emerge because of all the 'instanceOf' calls.

I don't have a great solution.  I am not keen on the ones in the linked articles.  

http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/
https://blog.celogeek.com/201210/220/javascript-cross-frame-instanceof/

**Comment by awwright** [comment]
I'm closing this out because we're now using `Array.isArray` for differentiating between objects and arrays; for other things, please open a new issue and provide a code sample illustrating what you're trying to do.
