### ISSUE TITLE
Support "uri-reference" format

### ISSUE THREAD

**Issue by gmcnaught** [tdegrunt/jsonschema#200]
The uri specification seems to expect fully qualified URLs, wheras a URI can be relative path, and can also be not parsable by node's url library. 
Looking at the regular expression below, there seems to be a lot of assumption as to what type of URI might be matched.

https://github.com/tdegrunt/jsonschema/blob/master/lib/helpers.js#L123

For a better URI regular expression, this appears to generate a regular expression that matches more of the URI RFC:
https://github.com/DavidTPate/rfc-3986

**Comment by awwright** [comment]
Can you please provide some test cases?

[JSON Schema Validation](https://datatracker.ietf.org/doc/draft-wright-json-schema-validation/) references the `URI` production of RFC3986, which is:

    URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

The kind that allows relative references is called a URI Reference, which is the "uriref" format in JSON Schema. The syntax for a URI Reference is:

      URI-reference = URI / relative-ref

Though it doesn't seem to be implemented here yet...

**Comment by handrews** [comment]
@gmcnaught The latest draft of JSON Schema, released a few weeks ago, adds the `"uri-reference"` format for the use case you want here.

**Comment by awwright** [comment]
Implemented in 817a367d7318892d5e9154eb933f54460086dfe3
