### ISSUE TITLE
required property not following V5 draft

### ISSUE THREAD

**Issue by gkorland** [tdegrunt/jsonschema#201]
According to the code required is also supported as part of the property ([attribute.js:478](https://github.com/tdegrunt/jsonschema/blob/master/lib/attribute.js#L478)) as a boolean property. 

According to the V5 draft [requried](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.15) must be an array.

**Comment by awwright** [comment]
@gkorland JSON Schema validators are allowed to support additional features as desired.

In the case of boolean "required", this is to support JSON Schema documents written against older drafts that had a boolean "required" keyword.

**Comment by gkorland** [comment]
Thanks, are you going to keep this feature or follow v5 and drop it?

**Comment by awwright** [comment]
@gkorland There's an interest in preserving backwards-compatibility, especially if it's not too difficult. Is there any compelling reason to drop it?

**Comment by gkorland** [comment]
We were using other tools which utilize the same schemas and got errors on
those attributes

**Comment by leibale** [comment]
@awwright at least throw depreciation error

**Comment by awwright** [comment]
@gkorland @leibale Can you give some use-cases or examples of what you're running into?

**Comment by leibale** [comment]
https://github.com/json-schema-faker/json-schema-faker/issues/237

**Comment by awwright** [comment]
Lacking a compelling reason to remove reverse-compatibility support, I'll close this out.

The authority on what makes a valid schema is the JSON Schema documents, see <http://json-schema.org/>.
