### ISSUE TITLE
Verifying that an object does _not_ have a certain property?

### ISSUE THREAD

**Issue by dadambickford** [tdegrunt/jsonschema#207]
I wasn't able to find anything in the docs about this, is it possible? or is there a better way to think about this?

I was thinking something like:
```
let schema = {
  "id": "/test",
  "type": "object",
  "restrictedProperties": [
    "cantHaveThis",
    "orThis"
  ]
}
```

Main issue I'm trying to extra double check is accidental nesting

making sure:
```
{
  test: {
    props: {}
  }
}
```
isn't accidentally:
```
{
  test: {
    test: {
      props: {}
    }
  }
}
```

Thanks in advance

**Comment by inallib** [comment]
I was even trying to get a way if we can can validate an expected prop / key exist. Like

let expectedJson = {
id:1,
name: "xxx",
salary: 22
} 


let actualJson = {
id:1,
name: "xxx",
sal: 22
} 

so , the validation should fail since in actual key is "sal" where is expection was "salary"

**Comment by nbering** [comment]
@inallib If "salary" is not a required field, then "sal" would pass validation, since in the v4 draft of jsonSchema (which this library states as the support level in the README), the specification suggests that properties not part of the schema should just be ignored.

**Comment by awwright** [comment]
You can also do something like:

```javascript
{
"properties": {
   "cantHaveThis": false,
   "orThis": false
}
}
```
