### ISSUE TITLE
Can the module strictly validate instance?

### ISSUE THREAD

**Issue by mdikov** [tdegrunt/jsonschema#208]
Can I detect if the instance has additional properties that are not included in the schema?

**Comment by edweip3** [comment]
i'm curious about this too.  Would love to have this feature.

**Comment by mdikov** [comment]
@edweip3 I implemented my own checks. Basically you iterate over the instance and find if there is a property definition for it in the schema. Work well and it rather simple to implement outside of jsonschema.

**Comment by core-process** [comment]
https://github.com/tdegrunt/jsonschema/blob/master/examples/all.js#L102

**Comment by awwright** [comment]
@mdikov Is this different than the "additionalProperties" keyword?

**Comment by dominique-mueller** [comment]
`additionalProperties` set to `false` works like a charm!

**Comment by awwright** [comment]
Closing because "additionalProperties" seems to be the keyword to use for this.

For additional help on writing schemas, check out the resources on https://json-schema.org/
