### ISSUE TITLE
jsonschema fails to validate objects from a different scope

### ISSUE THREAD

**Issue by dantman** [tdegrunt/jsonschema#209]
In the `properties` handler `instanceof Object` is used.

> https://github.com/tdegrunt/jsonschema/blob/master/lib/attribute.js#L186
> ```
> if(instance === undefined || !(instance instanceof Object)) return;
> ```

This fails if the object does not inherit from `Object`.

The classic case where this will fail is in a browser when the object comes from another frame or in v8/node where multiple vms/contexts are used. However there are other cases where this can fail.

* Node.js' querystring.parse returns objects that do not inherit from `Object`
* Objects created using `Object.create(null)` do not have a prototype and hence are not `instanceof Object`
  * This one is especially important because a common reason for using `Object.create(null)` is when working with objects that are actually arbitrary key=>value objects so they are not polluted by Object.prototype, ie: the exact type of object jsonschema is supposed to be validating.

This is wrong and dangerous behaviour by jsonschema; When jsonschema encounters an object that does not inherit from `Object` it completely skips over all validation for the properties of that object and says it's ok. There is absolutely no warning to the application developer that the schema validation is passing invalid (and in some contexts, malicious) data through as ok.

#145 It seems that years ago someone tried fixing this but it never got merged.

**Comment by awwright** [comment]
@dantman I'll take a look at this for sure.

But please note that the library is only tested against JSON (i.e. a string of bytes, not a javascript object literal), and is only guaranteed to work correctly for literals that are serializable to JSON.

Also note it's not difficult to construct schemas that consume excessive system resources to validate, such as [regular expressions](https://en.wikipedia.org/wiki/ReDoS) -- I wouldn't parse user-provided third party schemas on a production server, for instance, unless the implementation was specifically hardened against such attack vectors (I don't know of any implementations that are).

**Comment by RoboPhred** [comment]
Just got bit by this, due to having sandboxed code generating the objects inside a v8 context.

Interestingly, the failure ends up indicating that the object is valid.  If it detected it was a non-object, shouldn't it indicate a failure?
The specific line pointed to is in validators.properties, but I also have a "required": [] validator in there, which should probably be the thing to reject it (as a thing that is not an object naturally wont have properties, and so cannot match the required props)

**Comment by awwright** [comment]
@RoboPhred Noted, thanks!

**Comment by awwright** [comment]
We're not using `instanceof Object` anymore, so I'm going to close this out. If this is still a problem, please file a new issue with a code sample so I can take a closer look.
