### ISSUE TITLE
oneOf, anyOf and nestedErrors not behaving as expected

### ISSUE THREAD

**Issue by martinp999** [tdegrunt/jsonschema#210]
The problem that I am having is that oneOf and anyOf do not absorb errors for what should be "under the hood" comparisons of their schema collection.  

Also, setting nestedErrors to **false** has no effect when throwErrors is **true**, but I'm not sure that matters - the advertised behaviour would be to silence _all_ errors, which would negate the act of validating in the first place.

Due to the fact that I am running jsonschema in mocha, I need the validator to throw errors when it _properly fails_, which is why I am setting options.throwError to true.

The problem is that it is throwing errors even though it is _not properly failing_.  By that I mean - 

```
const VALIDATOR = new Validator();
const SCHEMA = {
  id: '/FooSchema',
  oneOf: [
    {
      properties: {
        foo: {
          type: 'number'
        }
      },
      type: 'object'
    }, {
      properties: {
        foo: {
          type: 'string'
        }
      },
      type: 'object'
    }
  ]
};
const OBJECT1 = {
  foo: 12
};
const OBJECT2 = {
  foo: '12'
};

VALIDATOR.validate(OBJECT1, SCHEMA, {throwError: true, nestedErrors: false});

// **error thrown against schema 2**

VALIDATOR.validate(OBJECT2, SCHEMA, {throwError: true, nestedErrors: false});

// **error thrown against schema 1**

```
both OBJECT1 and OBJECT2 will throw an error, even though I have nestedErrors set to false (in fact it throws an error no matter what I do with nestedErrors - true, false, or not handed in).  OBJECT1 will fail on the second schema I have in my oneOf (because the validator needs to make sure that the first schema is the _only_ one it matches), OBJECT2 will fail on the first.

I get it that both objects need to be compared against each of the schemas, but individual fails within oneOf and anyOf should be swallowed and an error thrown only when _none_ of the schemas match.

**Comment by pschwyter** [comment]
I am running into the same problem!

**Comment by martinp999** [comment]
Without doing a pull request (apologies, I did look at the code but wasn't confident enough to make changes), I can only think to do it manually (n.b. not tested yet) -

```
const SCHEMA1 = {
  id: '/Schema1',
  properties: {
    foo: {
        type: 'number'
       }
    },
    type: 'object'
};

const SCHEMA2 = {
  id: '/Schema2',
  properties: {
    foo: {
        type: 'string'
       }
    },
    type: 'object'
};

const OBJECT1 = {
  foo: 12
};

const OBJECT2 = {
  foo: '12'
};

function fValidateOneOf(schemas, object){
    let VALIDATOR = new Validator();
    for(schema in schemas){
        if(VALIDATOR.validate(object, schemas[schema], {throwError: false}).valid){
            return;
        }
    }
    throw new Error('object does not match any of the schemas provided');
}

fValidateOneOf([SCHEMA1, SCHEMA2], OBJECT1);
fValidateOneOf([SCHEMA1, SCHEMA2], OBJECT2);

```

So, if you were doing this as part of a larger schema, you'd leave out the bits about validating the collections, validate everything else and then use the brute force approach above for the collections separately.

**Comment by awwright** [comment]
I believe this was fixed in a recent release. I just added a test in 8c4f5ca4d2c073194cc979bbf9f76a1184c495a3.

If you think the behavior still needs to be changed, please open a new issue.
