### ISSUE TITLE
Add custom error messages

### ISSUE THREAD

**Issue by jzrchilel** [tdegrunt/jsonschema#212]
So I'm using jsonschema module, and everythings is working great. I just have the question if there's a way to add custom errors.
`
  apiBase: {
     type: 'string',
     minLength: 0,
     required: true,
     _minLength: 'The Api base should not be empty',
     _required: 'Api base is required'
},
`

**Comment by nbering** [comment]
Would that pass validation as a JSON-schema document? Just curious if they allow for extension, or if JSON-schema is of the opinion that additional fields are invalid.

**Comment by awwright** [comment]
@isafrus5 The suggested way to handle errors is to check for the keyword that failed validation and present an appropriate error message. This way, you can appropriate localize the error message too.

@nbering It is valid (unknown properties are ignored).

**Comment by awwright** [comment]
I think the best way to handle this is to treat the `name` property of the `ValidationError` as an untranslated string, and perform localization the same way you would in other parts of your application. I'll leave this open so I can add that example.

**Comment by awwright** [comment]
I added a paragraph on this in 9193f9d7aab0bbbed45d1db103eada148aee6b08

If anyone has any additional questions or comments, please open an issue so we can look into it.
