### ISSUE TITLE
JSONSchema `required` validation should specify propertyPath correctly when validating Object

### ISSUE THREAD

**Issue by mavarazy** [tdegrunt/jsonschema#215]
Here is a simple test to reproduce

      describe('object with required properties', function () {
          it('should specify path of invalid field', function () {
            var validation = this.validator.validate(
              { done: false },
              {
                type: "object",
                required: ["name"],
                properties: {
                  name: { type: "string" }
                }
              }
            );
            validation.propertyPath.should.equal("instance.name");
          })
        });

This is the result of investigating https://github.com/mozilla-services/react-jsonschema-form/issues/614, following through, it seems mistake was due to incorrect propertyPath in here

**Comment by awwright** [comment]
With the "required" keyword, it's testing that the object has or does not have a property in it.
The `ValidationError#argument` property will have the name of the missing property. The `propertyPath` is supposed to point to a path that exists, so I don't think it makes much sense to change this.

Let me know if you have any further comments or feedback.
