### ISSUE TITLE
required field in JSONSchema

### ISSUE THREAD

**Issue by MohammadShojaeinia** [tdegrunt/jsonschema#216]
Is it necessary to have required field in JSONSchema when defining a schema? when I defined my JSONSchema, always valid() method returned true, but after I added "required", it was correct! What was the problem? I asked it because in examples in Readme, "required" was not mentioned. 
Thanks!

**Comment by nbering** [comment]
It's not required to set required fields, but according to the json-schema specification fields are optional unless specified as required. It would still be possible to get a result of invalid without if, for example, there were a type mismatch or you had a pattern requirement on a string that failed.

**Comment by MohammadShojaeinia** [comment]
Thanks a lot! I'll check it again, but now I'm done and thanks about your
useful library!

Regards
Shojaeinia
