### ISSUE TITLE
Please document options that can be passed to the validate function

### ISSUE THREAD

**Issue by agrishkan** [tdegrunt/jsonschema#223]
The current README file mentions options such as throwError and nestedErrors. Others, unfortunately, can be learned only by looking at the source code.

Please add the options and their descriptions to the README.

The others I found:
- propertyName
- base
- skipAttributes
- allowUnknownAttributes
- rewrite
- disableFormat

**Comment by awwright** [comment]
Some of these are internal and subject to change...

I'll begin working on fixing some of the issues around them, then
documenting them though.

**Comment by pszabop** [comment]
thanks for when this is fixed.  It took me 10 minutes to find `allowUnknownAttributes` which is a very important option for my use case (or anyone who wants to be resistant to storing data they didn't validate... which should be everyone using a JSON store...)

**Comment by awwright** [comment]
Progress:

- [ ] skipAttributes?: string[];
- [ ] allowUnknownAttributes?: boolean;
- [ ] rewrite?: RewriteFunction;
- [ ] propertyName?: string;
- [ ] base?: string;
- [ ] throwError?: boolean;
- [ ] nestedErrors?: boolean;

**Comment by awwright** [comment]
All of these keywords should now be mentioned in the README as of fbd9e2bebcfa9a8379929efe1434f24e5d829419

Please open a new issue if there's anything missing!
