### ISSUE TITLE
I need properties from date type to pass json schema validation

### ISSUE THREAD

**Issue by boyandimitrov** [tdegrunt/jsonschema#227]
I know it's against the json specification but is there an option to provide entirely custom validation.

My case is following:

I have very simple schema to validate data before storing it in mongodb

    "title": "ticket",
    "type": "object",
    "properties": {
        "_id"    : {"type": "string"},
        "created": {"type": "string", "format": "date-time"} 
    },
    "additionalProperties" : false

created property has an index and time-to-live (ttl) on it. I need this property to be of type date, otherwise it will not work. although for this specific case date type is very important, it's equally important to be able to store date properties as dates and not as a string, so you can group by intuitively for example.

the problem is that json validation does not allow properties from date type. Date can pass only as string and because mongodb is "schemaless" when you save a string it's a string even if it looks like date, so expiresAfterSeconds (ttl) does not work.

So it's a vicious circle. 

I tried several implementations so far and neither seems to work or are good enough.

1. I created custom attribute

   ` validator.attributes.skipdate = function validateSjkipDate(instance, schema, options, ctx) {
            if(!_.isDate(instance) || !schema.skipdate) {
                  return 'date type is required';
            }
    };`

this could work but the main validations fails with instance is not from type string.

2. I could traverse the object before save and after validation, so I can fix the types. Although this would require some work (schema can reference another schemas), document can have sub objects or even array of sub objects this could solve my problem. After all how fast are updates is not important for me. The problem is that I have to do this on read also because it will be unacceptable  to read the document (now my date properties would be a real dates) and I will fail on update as schema validation will throw.

3. I can set additionalProperties = true and remove date types from validation but this is rather messy, because It's not the real schema anymore.

So i feel the most elegant way would be to have a real custom validation.

**Comment by razzdasari** [comment]
Add this code at end of the file  /bin/validator.js
types.date = function testDate(instance) {
  return helpers.FORMAT_REGEXPS.date.test(instance);
};

And then mention properties
"properties": {
    "_id"    : {"type": "string"},
    "created": {"type": "date"} 
}
