### ISSUE TITLE
Null is not validated when type is string

### ISSUE THREAD

**Issue by sojimon** [tdegrunt/jsonschema#230]
I am trying to validate `username`.It is passed as " ". And I declared `username` of type `string`.And there is validation message.I need to allow " " as an invalid value . 
`
 var statusSchema = {
        "id": "/status",
        "type": "object",
        "properties": {
          "username": {"type": "string",
            "not": {"type":  "null"}
            },
          "password": {"type": "string"},
          "action_code": {"type": "string"},
          "prev_history_id": {"type": "string"}
        },
        "required": ["username","password","action_code","prev_history_id"]
    };
`

**Comment by roccomuso** [comment]
did you find a workaround?

**Comment by awwright** [comment]
@sojimon That looks like a job for regular expressions using the "pattern" keyword, and maybe the "not" keyword.

This would be a good question for a general JSON Schema forum.
