### ISSUE TITLE
Extend with custom keyword to support nullable based on Open API 3 Specification

### ISSUE THREAD

**Issue by khusamov** [tdegrunt/jsonschema#231]
We use internaly Swagger aka Open API. The schema differs from the JSON Schema defintion.

Eg. the type can only be one type instead of an array of types line
```javascript
"type":["string","null"]
```
To support nullable values you must define
```javascript
"type":"string", nullable: true
```

I tried to do this, but I did not get a working code:
```javascript
var _ = require('lodash');
var Validator = require('jsonschema').Validator;
var v = new Validator();

v.attributes.nullable = function validateContains(instance, schema, options, ctx) {
	if (_.isArray(schema.type) && schema.type.includes('null')) return;
	if (schema.nullable) return;
	if (instance === null) return 'Should not be equal to null';
};

var schema = {
	"properties": {
		"foo": { 
			"type": "string", 
			"nullable": true 
		} 
	} 
};
var data = {"foo": null};

var result = v.validate(data, schema);

if (result.valid) {
	console.log(result.valid)
} else {
	console.log(result)
}

// Expected result.valid == true
```
How can I extend the existing type checking to prevent errors, when the value is null, based on the new nullable keyword?

I understand, that adding new keyword make the validation stronger. But how can I weaken the existing validation?

**Comment by awwright** [comment]
Hmm, I've been in a handful of discussions with Swagger about JSON Schema but I wasn't aware they were doing it like this. Let me see what their thinking is.

**Comment by favasconcelos** [comment]
Is there any updates on this?

**Comment by awwright** [comment]
We've been moving to have OpenAPI use native JSON Schema keywords. It's not really feasible to implement this because instead of representing a restriction on an instance, it represents a value that's allowed in addition to the "type" keyword. As a general rule, all keywords in JSON Schema add limitations.

Some minor postprocessing of the OpenAPI description should turn it into a standard JSON Schema: if you see `nullable==true` then set `type := [ type, "null" ]`

What are you trying to do exactly, @favasconcelos ?

**Comment by favasconcelos** [comment]
Your proposal was something that in the end I finally managed to implement. But to give some context the goal behind everything was to validate the result of an API call against the swagger JSON schema using the lib without the need to modify the schema itself.

**Comment by awwright** [comment]
OpenAPI no longer uses "nullable" but instead follows the JSON Schema "type" keyword exactly.

Some news on this:
* https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0
* https://twitter.com/apisyouwonthate/status/1266298393577443331

Feel free to let me know any comments or other thoughts on this.
