### ISSUE TITLE
Empty string is a required field

### ISSUE THREAD

**Issue by isychev** [tdegrunt/jsonschema#233]
Hello
Now there is such code

```
schema.required.forEach(function(n){
      if(instance[n]===undefined){
        result.addError({
          name: 'required',
          argument: n,
          message: "requires property " + JSON.stringify(n),
        });
      }
    });
```
If I send an empty string to the validation, the validator will return that the line is valid.

Can I make a change?
` if(instance[n]===undefined && instance[n]===''){`

**Comment by awwright** [comment]
@isychev Please provide an example program, with expected and actual output.

I don't think `instance[n]===undefined && instance[n]===''` will do anything, that will always evaluate `false`.

**Comment by isychev** [comment]
@awwright Sorry, this is of course a typo
`instance[n]===undefined || instance[n]===''`
Please see my example [https://jsfiddle.net/aqa75j15/](https://jsfiddle.net/aqa75j15/)
Value in empty input can't be undefined,  it is always empty string
If we send an empty string to the validation, we get a valid form

**Comment by awwright** [comment]
@isychev An empty string is still a defined value in JSON Schema. You're probably looking for the `minLength` keyword?

**Comment by isychev** [comment]
@awwright  For string fields may not seem an error "Required field" will always error "minLength"?

**Comment by isychev** [comment]
@awwright or if the field exists in the data object it is it will always pass the validation `required`
