### ISSUE TITLE
Returning invalid results

### ISSUE THREAD

**Issue by goldytech** [tdegrunt/jsonschema#234]
Hi 

Below is my sample code. My expectations this should return me false. But it is returning true.
My requirements are that the instance should not have any unknown attributes which are not defined in schema also it should validate the type of data. The instance should not contain a string value for the attribute when the required type should be integer.

```
var Validator = require('jsonschema').Validator
var v = new Validator()


var personSchema = {
  'id': '/SimpleObj',
  'type': 'object',
  'properties': {
    'firstName': {'type': 'string'},
    'age': {'type': 'integer'},
    'dateofBirth': {'type': 'date-time'}
  },
  'required': ['firstName']
}
let person = {
  firstName: 'Maq',
  m: 'j20'
  
}

console.log(v.validate(person, personSchema, {allowUnknownAttributes: false, disabaleFormat: false}))
```

**Comment by nbering** [comment]
It's not very well documented, but here's a comment that might explain things.
https://github.com/tdegrunt/jsonschema/blob/6d304da6d12146247fca55d33ad1fea2b77f1ceb/lib/validator.js#L212-L215

Also, unknown properties on the object being valid are acceptable according to the JSON schema specification. I believe the latest draft has some proposed validator options to turn that on or off. I believe there is another library that does do "strict mode", but can't remember the name off the top of my head.

**Comment by awwright** [comment]
Hi @goldytech, @nbering hit the nail on the head.

"attributes" are better known as schema keywords. Setting `allowUnknownAttributes: false` just causes the validator to throw on an unknown schema keyword, instead of ignoring it; and this is different than an instance property. For prohibiting unknown instance properties, look at the `additionalProperties: false` keyword (which you would provide in a schema).

**Comment by tdegrunt** [comment]
Seems resolved, closing this issue

**Comment by BrandonHalig** [comment]
> Hi @goldytech, @nbering hit the nail on the head.
> 
> "attributes" are better known as schema keywords. Setting `allowUnknownAttributes: false` just causes the validator to throw on an unknown schema keyword, instead of ignoring it; and this is different than an instance property. For prohibiting unknown instance properties, look at the `additionalProperties: false` keyword (which you would provide in a schema).

Thanks, "additionalProperties" doesn't even seem to be in their own documents https://www.npmjs.com/package/jsonschema
