### ISSUE TITLE
Make jsonschema compatible with swagger-schema-official

### ISSUE THREAD

**Issue by Dahaden** [tdegrunt/jsonschema#241]
Currently, swagger-schema-official is at v7 while jsonschema is at v4

The main issue I have is the types are not compatible. 

While I do understand that it is primarily used for v4 (as stated) I would like to add the ability to at least be compatible with swagger-schema-official (while still working with v4)

**Comment by awwright** [comment]
Can you provide some details on what you're looking for please?
