### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by intelliot** [tdegrunt/jsonschema#252]
It's difficult to compare between versions because there have been no tagged releases since v1.0.1. See https://github.com/tdegrunt/jsonschema/releases

**Comment by awwright** [comment]
I pushed out two tags that seem to have gotten lost in a `git push`. I didn't make the other releases, I don't think. I'll look at tagging them.

**Comment by intelliot** [comment]
If you have the tags locally, you can try something like:

`git push origin --tags`

See “Sharing Tags” at https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by awwright** [comment]
@intelliot Yeah, that's what I just did. I believe @tdegrunt has the other tags held captive somewhere, though ;)

**Comment by awwright** [comment]
I pushed five new tags corresponding to when the package.json was updated. Note, there was no `1.2.1` release for some reason.
