### ISSUE TITLE
$Ref is not working

### ISSUE THREAD

**Issue by sudoapt123** [tdegrunt/jsonschema#255]
Ref Schema:
VType.json
```
{
    "$schema":"http://json-schema.org/draft-04/schema#",
    "enum":
    [
        "VT_STATIC", 
        "VT_STATIC_SVLAN", 
        "VT_GVRP"
    ]
}
```
Code:
```
var Validator = require('jsonschema').Validator;
var v = new Validator();
var instance = {
    "v_id": 10,
    "name": "json schema",
    "type": "VT_STATIC"
};
var schema= 
  {
    "$schema": "http://json-schema.org/draft-04/schema#", 
    "type": "object", 
    "required" :["id", "name"],
    "properties":
    {
        "v_id":
        {
            "minimum": 1, 
            "maximum": 4094, 
            "type": "integer"
        }, 
        "name":
        {
            "type": "string", 
            "maxLength": 32
        },
        "type":
        {
            "$ref":"/user/abc/schema/VType.json"
        }
    }
}; 
console.log(v.validate(instance, schema));
```
Here, I am getting error for $ref. 
Error:  no such schema </user/abc/schema/VType.json>. I am sure that the path is correct for the VType.json schema.

**Comment by awwright** [comment]
@sudoapt123 What is the path relative to? There's no "id" in that document to anchor the relative reference `/user/abc/schema/VType.json` so it could be resolving to anything.

This could/should be indicated with a clearer error message, so I'll take a look at that too.

**Comment by sudoapt123** [comment]
Hello, the error message is: **no such schema </user/abc/schema/VType.json>** . And, I don't think "id" is necessary in the document. The given schemas are also correct to the best of my knowledge.

**Comment by awwright** [comment]
@sudoapt123 Also, you probably need to import the schemas. Check https://github.com/tdegrunt/jsonschema#dereferencing-schemas for more information. Apologies for not catching that earlier.

**Comment by DonMehdi** [comment]
Have you found any solution for that ?

**Comment by awwright** [comment]
This issue typically happens when the schema URI is not a full, valid URI.

In order to work predictably, it must be a full URI such as `http://example.com/schema.json`. #205 intends to provide a more descriptive error message for exactly these cases.

If you have tried this and you are still having problems, please open a new issue and provide the code you are using along with expected and actual output.
