### ISSUE TITLE
Add validation for UUID

### ISSUE THREAD

**Issue by tomergo1** [tdegrunt/jsonschema#262]
Please add validation for UUID (all types)

**Comment by vujovicigor** [comment]
Add custom format function:
`const Validator = require('jsonschema').Validator;
let uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i
Validator.prototype.customFormats.uuid = function(input) {
  return uuidRegex.test(input) 
};`

Usage:
`{
      "type": "string",
      "format": "uuid"
}`
