### ISSUE TITLE
`const` does not appear as a valid property on `Schema` in index.d.ts

### ISSUE THREAD

**Issue by grubeeric** [tdegrunt/jsonschema#271]
The types file `index.d.ts` does not expose the `const` property in any meaningful way on the `Schema` interface [here](https://github.com/tdegrunt/jsonschema/blob/master/lib/index.d.ts#L49). As a result, if trying to create a validator with a schema which uses `const`, it will give a type error complaining that the schema does not match `Schema`. Would a pull request adding `const?: any` to the `Schema` interface be accepted? I can fall back to using an enum with only the one value in it, but `const` would be preferred. 

Example:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "example-schema.json",
    "type": "object",
    "properties": {
        "someProperty": {
            "const": "constant_property"
        }
    }
}
```

```ts
import * as jsonschema from "jsonschema";
import schema from "./schema.json";

const validator = new jsonschema.Validator();
validator.addSchema(schema, "/schema.json");
```

The above will complain that `schema` has no properties in common with `Schema`. If i change the schema to 
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "example-schema.json",
    "type": "object",
    "properties": {
        "someProperty": {
            "enum": ["constant_property"]
        }
    }
}
```

it will no longer complain.

**Comment by awwright** [comment]
872935b4a856a0f69d0363d5f52e1c47789725d5 should resolve this, and will be available in the next release.
