### ISSUE TITLE
How to add a default value to the existing object if the key is not present

### ISSUE THREAD

**Issue by Vinay328** [tdegrunt/jsonschema#276]
const validate = require('jsonschema').validate;

var schema = {
    "type": "object",
    "properties": {
        "age": { "type": "number" },
        "bar": { "type": "string", "default": "baz"}
    },
    "required": [ "foo", "bar" ]
};

var obj = { "age": 15 };

const schemaValidation = validate(obj,schema);
console.log(schemaValidation.errors);
console.log(obj);  // o/p -> {"age": "15"}
//what I need is  {"age": "15", "bar": "baz"}

Hi, can anyone help me how to add the default value to the obj variable here?

**Comment by tdegrunt** [comment]
jsonschema will not add a default, in fact it will report a validation error as it should according to the specification.

Fixing the incoming json is outside the scope of this project.
But checking the validation errors for entries with name 'required' in combination with the schema gives you information you can use to add it.

Tom

**Comment by Vinay328** [comment]
Thank you tom for your quick reply.
