### ISSUE TITLE
Trim property before validation

### ISSUE THREAD

**Issue by EdoElgx** [tdegrunt/jsonschema#278]
Hi,

Is there a way to trim a string property right before validation?

I need space/tab strings to be considered as empty strings, so it doesn't pass a minLength: 1 rule.

Thanks.

**Comment by awwright** [comment]
@EdoElgx No, JSON Schema (either the specification or this implementation) doesn't offer any way to perform operations on the data as such; however you can use a regular expression to accomplish that, or (my personal recommendation) you can write a function in your application that normalizes the values first.
`pattern: "\S"` should suffice (this match the first non-whitespace character, or fail validation if it can't find any)

**Comment by EdoElgx** [comment]
@awwright Thanks. That will do.
