### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by jabhishek** [tdegrunt/jsonschema#279]
Just wondering if this project is still maintained. I see that there are lots of useful PRs still waiting to be merged for a long time.

**Comment by tdegrunt** [comment]
Closing, not constructive, nor helpful

**Comment by webarthur** [comment]
I think questions without answers are not constructive...

**Comment by webarthur** [comment]
+1

=/

**Comment by webarthur** [comment]
There is some maintained module that is based on jsonchema?
