### ISSUE TITLE
1.2.4 release does not contain update to type definition

### ISSUE THREAD

**Issue by jaredh159** [tdegrunt/jsonschema#286]
1.2.4 is missing this commit: 5e51b8236c5d7b04f799990af5bade5ee0e1e270

See: https://github.com/tdegrunt/jsonschema/blob/9abc4f5d0420759c5606b597bae954f47a13e1ac/lib/index.d.ts

(9abc4f5d is the commit pointed at by the `1.2.4` release)

Any chance we could get a 1.2.5 release?  I'm not sure why 1.2.4 doesn't have that commit, it seems to have been tagged _after_ the commit that added the `stack: string` line...

Thanks for the great library!

**Comment by awwright** [comment]
Hmmm, I'll take a look at it

**Comment by awwright** [comment]
@jaredh159 If you missed it, this should be in since `v1.2.5`. I'm closing this out now, but please file a new issue if there's anything else missing.
