### ISSUE TITLE
Plans to support latest JSON Schema 2019-09 version?

### ISSUE THREAD

**Issue by chaeron** [tdegrunt/jsonschema#294]
Do you have any plans to support the latest JSON Schema 2019-09 version?

**Comment by awwright** [comment]
@chaeron Yes!

**Comment by awwright** [comment]
@chaeron Good question... It's one of the next things I'm working on. If you have a specific feature you're looking for, thumb up or drop a comment in an issue, or file a new issue if necessary, and I can look at that first.
