### ISSUE TITLE
csp policy blocking script

### ISSUE THREAD

**Issue by sid786** [tdegrunt/jsonschema#296]
Error compiling schema, function code: var refVal1 = refVal[1]; var validate = function(data, dataPath, parentData, parentDataProperty, rootData) { 'use strict';  var vErrors = null;  var errors = 0;            var errs_1 = errors;    var errs_2 = errors; if ((typeof data !== "number" || (data % 1) || data !== data)) {  var err =  { keyword: 'type' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/positiveInteger/type' , params: { type: 'integer' }  , message: 'should be integer'  , schema: refVal[1].type , parentSchema: refVal[1] , data: data  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }  if (typeof data === "number") {    if (  data < 0 || data !== data) {  var err =  { keyword: 'minimum' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/positiveInteger/minimum' , params: { comparison: '>=', limit: 0, exclusive: false }  , message: 'should be >= 0' , schema:  0         , parentSchema: refVal[1] , data: data  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }   }  var valid2 = errors === errs_2;   var valid1 = errors === errs_1;   validate.errors = vErrors;  return errors === 0;        }; return validate;
F @ main.e6cc2c184e2eb1d54b53.js:1
s @ main.e6cc2c184e2eb1d54b53.js:1
L @ main.e6cc2c184e2eb1d54b53.js:1
e.exports @ main.e6cc2c184e2eb1d54b53.js:1
e.exports @ main.e6cc2c184e2eb1d54b53.js:1
e.exports @ main.e6cc2c184e2eb1d54b53.js:1
e.exports @ main.e6cc2c184e2eb1d54b53.js:1
F @ main.e6cc2c184e2eb1d54b53.js:1
e @ main.e6cc2c184e2eb1d54b53.js:1
v._compile @ main.e6cc2c184e2eb1d54b53.js:1
v.getSchema @ main.e6cc2c184e2eb1d54b53.js:1
v.validate @ main.e6cc2c184e2eb1d54b53.js:1
v.validateSchema @ main.e6cc2c184e2eb1d54b53.js:1
v._addSchema @ main.e6cc2c184e2eb1d54b53.js:1
v.addSchema @ main.e6cc2c184e2eb1d54b53.js:1
v.addMetaSchema @ main.e6cc2c184e2eb1d54b53.js:1
f.setSchema @ main.e6cc2c184e2eb1d54b53.js:1
g.create @ main.e6cc2c184e2eb1d54b53.js:1
f.setMode @ main.e6cc2c184e2eb1d54b53.js:1
f._create @ main.e6cc2c184e2eb1d54b53.js:1
f @ main.e6cc2c184e2eb1d54b53.js:1
e.ngOnInit @ main.e6cc2c184e2eb1d54b53.js:1
(anonymous) @ main.e6cc2c184e2eb1d54b53.js:1
(anonymous) @ main.e6cc2c184e2eb1d54b53.js:1
$_ @ main.e6cc2c184e2eb1d54b53.js:1
mw @ main.e6cc2c184e2eb1d54b53.js:1
(anonymous) @ main.e6cc2c184e2eb1d54b53.js:1
updateDirectives @ main.e6cc2c184e2eb1d54b53.js:1
H_ @ main.e6cc2c184e2eb1d54b53.js:1
Z_ @ main.e6cc2c184e2eb1d54b53.js:1
J_ @ main.e6cc2c184e2eb1d54b53.js:1
H_ @ main.e6cc2c184e2eb1d54b53.js:1
Z_ @ main.e6cc2c184e2eb1d54b53.js:1
K_ @ main.e6cc2c184e2eb1d54b53.js:1
H_ @ main.e6cc2c184e2eb1d54b53.js:1
e.detectChanges @ main.e6cc2c184e2eb1d54b53.js:1
e.tick @ main.e6cc2c184e2eb1d54b53.js:1
(anonymous) @ main.e6cc2c184e2eb1d54b53.js:1
e.invoke @ polyfills.0049dfda0d1bcdbcd2bf.js:1
onInvoke @ main.e6cc2c184e2eb1d54b53.js:1
e.invoke @ polyfills.0049dfda0d1bcdbcd2bf.js:1
t.run @ polyfills.0049dfda0d1bcdbcd2bf.js:1
e.run @ main.e6cc2c184e2eb1d54b53.js:1
next @ main.e6cc2c184e2eb1d54b53.js:1
o @ main.e6cc2c184e2eb1d54b53.js:1
t.__tryOrUnsub @ main.e6cc2c184e2eb1d54b53.js:1
t.next @ main.e6cc2c184e2eb1d54b53.js:1
t._next @ main.e6cc2c184e2eb1d54b53.js:1
t.next @ main.e6cc2c184e2eb1d54b53.js:1
t.next @ main.e6cc2c184e2eb1d54b53.js:1
t.emit @ main.e6cc2c184e2eb1d54b53.js:1
ly @ main.e6cc2c184e2eb1d54b53.js:1
sy @ main.e6cc2c184e2eb1d54b53.js:1
onInvokeTask @ main.e6cc2c184e2eb1d54b53.js:1
e.invokeTask @ polyfills.0049dfda0d1bcdbcd2bf.js:1
t.runTask @ polyfills.0049dfda0d1bcdbcd2bf.js:1
t.invokeTask @ polyfills.0049dfda0d1bcdbcd2bf.js:1
b @ polyfills.0049dfda0d1bcdbcd2bf.js:1
_ @ polyfills.0049dfda0d1bcdbcd2bf.js:1
Show 29 more frames
main.e6cc2c184e2eb1d54b53.js:1 Failed to create an instance of Ajv, JSON Schema validation is not available. Please use a JSONEditor bundle including Ajv, or pass an instance of Ajv as via the configuration option `ajv`.
f.setSchema @ main.e6cc2c184e2eb1d54b53.js:1
g.create @ main.e6cc2c184e2eb1d54b53.js:1
f.setMode @ main.e6cc2c184e2eb1d54b53.js:1
f._create @ main.e6cc2c184e2eb1d54b53.js:1
f @ main.e6cc2c184e2eb1d54b53.js:1
e.ngOnInit @ main.e6cc2c184e2eb1d54b53.js:1
(anonymous) @ main.e6cc2c184e2eb1d54b53.js:1
(anonymous) @ main.e6cc2c184e2eb1d54b53.js:1
$_ @ main.e6cc2c184e2eb1d54b53.js:1
mw @ main.e6cc2c184e2eb1d54b53.js:1
(anonymous) @ main.e6cc2c184e2eb1d54b53.js:1
updateDirectives @ main.e6cc2c184e2eb1d54b53.js:1
H_ @ main.e6cc2c184e2eb1d54b53.js:1
Z_ @ main.e6cc2c184e2eb1d54b53.js:1
J_ @ main.e6cc2c184e2eb1d54b53.js:1
H_ @ main.e6cc2c184e2eb1d54b53.js:1
Z_ @ main.e6cc2c184e2eb1d54b53.js:1
K_ @ main.e6cc2c184e2eb1d54b53.js:1
H_ @ main.e6cc2c184e2eb1d54b53.js:1
e.detectChanges @ main.e6cc2c184e2eb1d54b53.js:1
e.tick @ main.e6cc2c184e2eb1d54b53.js:1
(anonymous) @ main.e6cc2c184e2eb1d54b53.js:1
e.invoke @ polyfills.0049dfda0d1bcdbcd2bf.js:1
onInvoke @ main.e6cc2c184e2eb1d54b53.js:1
e.invoke @ polyfills.0049dfda0d1bcdbcd2bf.js:1
t.run @ polyfills.0049dfda0d1bcdbcd2bf.js:1
e.run @ main.e6cc2c184e2eb1d54b53.js:1
next @ main.e6cc2c184e2eb1d54b53.js:1
o @ main.e6cc2c184e2eb1d54b53.js:1
t.__tryOrUnsub @ main.e6cc2c184e2eb1d54b53.js:1
t.next @ main.e6cc2c184e2eb1d54b53.js:1
t._next @ main.e6cc2c184e2eb1d54b53.js:1
t.next @ main.e6cc2c184e2eb1d54b53.js:1
t.next @ main.e6cc2c184e2eb1d54b53.js:1
t.emit @ main.e6cc2c184e2eb1d54b53.js:1
ly @ main.e6cc2c184e2eb1d54b53.js:1
sy @ main.e6cc2c184e2eb1d54b53.js:1
onInvokeTask @ main.e6cc2c184e2eb1d54b53.js:1
e.invokeTask @ polyfills.0049dfda0d1bcdbcd2bf.js:1
t.runTask @ polyfills.0049dfda0d1bcdbcd2bf.js:1
t.invokeTask @ polyfills.0049dfda0d1bcdbcd2bf.js:1
b @ polyfills.0049dfda0d1bcdbcd2bf.js:1
_ @ polyfills.0049dfda0d1bcdbcd2bf.js:1
Show 13 more frames
main.e6cc2c184e2eb1d54b53.js:1 Error compiling schema, function code: var refVal1 = refVal[1];var refVal2 = refVal[2]; var validate = function(data, dataPath, parentData, parentDataProperty, rootData) { 'use strict';  var vErrors = null;  var errors = 0;            var errs_1 = errors;    var errs_2 = errors; if ((typeof data !== "number" || (data % 1) || data !== data)) {  var err =  { keyword: 'type' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/type' , params: { type: 'integer' }  , message: 'should be integer'  , schema: refVal[2].type , parentSchema: refVal[2] , data: data  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }  if (typeof data === "number") {    if (  data < 0 || data !== data) {  var err =  { keyword: 'minimum' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/minimum' , params: { comparison: '>=', limit: 0, exclusive: false }  , message: 'should be >= 0' , schema:  0         , parentSchema: refVal[2] , data: data  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }   }  var valid2 = errors === errs_2;   var valid1 = errors === errs_1;   validate.errors = vErrors;  return errors === 0;        }; return validate;

 Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'

**Comment by awwright** [comment]
Are you sure you're using the "jsonschema" package? We don't use eval.

**Comment by tdegrunt** [comment]
The text above mentions AJV - https://github.com/epoberezkin/ajv. Closing.
