### ISSUE TITLE
`uniqueItems: false` has no effect for array validation

### ISSUE THREAD

**Issue by rkschamer** [tdegrunt/jsonschema#299]
# Problem

Even though setting `uniqueItems` to false the uniqueness validation seems not to be skipped. Consider the following example code:

```javascript

const Validator = require('jsonschema').Validator

function validate() {
    const schema = {
        type: Array,
        uniqueItems: false,
        items: {
            type: Object,
            properties: {
                name : { type: String, required: true }
            }
        }
    }
    
    const result = new Validator().validate([{ name: "first" }, { name: "first"}], schema)
    console.log(`Validation was successful: ${result.valid}`)
    for (const error of result.errors) {
        console.error(`${error.property} ${error.message}`)
    }
}

validate()
```

The output is:

```bash
Validation was successful: false
instance contains duplicate item
```

This matter was already mentioned by #91. The closing comment asked for a simple test, which is hereby provided

# Mitigation

If  `uniqueItems` is removed from the schema, the validation result does not contain the duplicate item error anymore.

**Comment by awwright** [comment]
This should be fixed with `8274e72044fc353d62a2d3fc425c7ed3e21b2f86` and available in the next release.
