### ISSUE TITLE
Dependencies for nested object properties

### ISSUE THREAD

**Issue by sromano88-svc** [tdegrunt/jsonschema#304]
I need to use the `dependencies` validation, but currently it works for a property that depends on another property.
Example, if a is present, then b must be present.
```
    "validateDependencies1": {
      "type": "object",
      "properties": { 
        "a": {"type": "string"},
        "b": {"type": "boolean"}
      },
      "dependencies": {"a": "b"}
    }
```
I need to make a dependency with a nested property.
Example, if a is present, then c property inside b object must be present.
```
    "validateDependencies1": {
      "type": "object",
      "properties": { 
        "a": {"type": "string"},
        "b": {"type": "object",
                "schema": {"c": {"type": "string"}}}
      },
      "dependencies": {"a": "b.c"}
    }
```
**The question I have if it is something that you consider could be useful.**

I know where to modify the code ([this line](https://github.com/tdegrunt/jsonschema/blob/b49eefa200ce0b8146f00ee8dc6153580573de19/lib/attribute.js#L719)), but need to be sure if it is going to be considered and merged in a new release.

Hope to hear from you.
It's a really great project.

Best regards,
Thanks.

**Comment by sromano88-svc** [comment]
Hi awwright, I see you assigned this issue to yourself.
Is there something I can help with?

**Comment by awwright** [comment]
@sromano88-svc "dependencies" can accept a map of schemas, like

```json
"dependencies": {
   "a": {
      "b": { "required": ["c"] },
      "required": ["b"]
   }
}
```

I think this is the closest you're going to get, because you're asking for a feature for the JSON Schema spec itself, and if you provided a value like `"b.c"` that already means something, it means you have to have a property named that: `{"b.c": true}` or whatever.

**Comment by sromano88-svc** [comment]
Thanks for your comments.

**Comment by awwright** [comment]
@sromano88-svc I'll close this out since this seems to be a suggestion for the JSON Schema spec itself, but check out https://json-schema.org/ if you have any further questions or suggestions. Or comment here if you think there's something I missed.
