### ISSUE TITLE
Generate schema from JSON Data

### ISSUE THREAD

**Issue by xyz-mtl** [tdegrunt/jsonschema#306]
Hi,

Do you know if this module can generate a schema from JSON data ?

Thx

**Comment by tdegrunt** [comment]
It doesn’t, sorry.

**Comment by xyz-mtl** [comment]
It's possible with this Library.  👍 

Package: NJsonSchema
Type: NJsonSchema.Generation.SampleJsonSchemaGenerator
The SampleJsonSchemaGenerator generates a JSON Schema from sample JSON data.

var schema = JsonSchema.FromSampleJson("...");
var schemaJson = schema.ToJson();

**Comment by awwright** [comment]
Also check out https://json-schema.org/implementations.html#generators-from-schemas on the official JSON Schema website
