### ISSUE TITLE
`const` possibly has a wrong typing

### ISSUE THREAD

**Issue by 3nvi** [tdegrunt/jsonschema#315]
Hey there,

Thanks for all your work  and for being responsive. 

I think I've spotted a small bug with the typings. Namely, I see that [`const` is typed as `any[]`](https://github.com/tdegrunt/jsonschema/commit/872935b4a856a0f69d0363d5f52e1c47789725d5) although the v6 draft states that a `const` [is a single value](https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values).

I can help with that, since it's an easy fix. Would you be willing to accept a PR for this?

**Comment by awwright** [comment]
@3nvi Yes that's right, nice catch.

I just made af3215433e4ce29146593fd18c44ea045a0498f2 to fix this, let me know if that looks correct.

If you know a good way to write tests for the TypeScript definitions, by all means please file a PR.

**Comment by 3nvi** [comment]
That looks perfect, thank you! Is  there a chance of a patch release in the coming days?

P.S. Unfortunately, I don't know of a  way to properly validate TS. Perhaps by comparing & cross-validating with the typings from `ajv` you can get some additional re-assurance

**Comment by awwright** [comment]
@3nvi One or two days, probably.
