### ISSUE TITLE
Determine value of readonly annotation

### ISSUE THREAD

**Issue by reneklootwijk** [tdegrunt/jsonschema#317]
Is there an easy way to determine the value of the readonly annotation for a specific property specified in the schema?

**Comment by awwright** [comment]
The library doesn't offer any way to read annotations specifically, however you can use a [rewrite hook](../../jsonschema#rewrite-hook) to do effectively the same thing. I would read the `schema` argument for schemas that contain a `readOnly` property, then store those `instance` values somewhere.

**Comment by reneklootwijk** [comment]
Thanks, that worked although I would have liked an easier way.

**Comment by awwright** [comment]
Better support for annotations is on the roadmap, and I opened #318 for this.

I'm closing this out since the problem seems to be solved. Please drop a comment or open an issue, if you have any further comments or suggestions.
