### ISSUE TITLE
Reuqired field no longer allows null

### ISSUE THREAD

**Issue by gandalfzyq** [tdegrunt/jsonschema#320]
In version 1.2.10, 
`validate` allow null when a field is set as required.

In version 1.2.11,
`validate` no longer allows null when a field is set as required.

Is this expected?

**Comment by awwright** [comment]
Hi @gandalfzyq, can you please provide a code sample, with expected and actual output?

**Comment by gandalfzyq** [comment]
Hi @awwright , to be more accurate,
in 1.2.10,
```
var jsonschema = require("jsonschema")

const { validate } = jsonschema;

const schema = {
    type: 'object',
    properties: {
        "could_be_null": {
            "anyOf": [
                {
                    "type": "string",
                },
                {
                    "type": null,
                }
            ]
        },
    },
    required: ['could_be_null'],
}

console.log(validate({ could_be_null: null }, schema));
```

This will not throw an exception. But in 1.2.11, I got the 
![image](https://user-images.githubusercontent.com/3908062/96270990-56c40800-0f9a-11eb-86cd-198b6cf58a1c.png)

**Comment by awwright** [comment]
@gandalfzyq Using a literal `null` for "type" is unsupported, and did not work consistently. Use the string `"null"` instead, this is the standard form expected by JSON Schema.

**Comment by gandalfzyq** [comment]
Ah ok, thanks!
