### ISSUE TITLE
Schema Validation Error Body

### ISSUE THREAD

**Issue by hassaniqbalKhan** [tdegrunt/jsonschema#329]
I am trying to validate json schema for the api response but on failure, I am unable to figure out the root cause of failure. I have attached the screenshot of the error. I need complete error for which the validation is failing.
<img width="633" alt="Screenshot 2020-12-03 at 4 48 25 PM" src="https://user-images.githubusercontent.com/73834788/101014374-9c0eba00-3587-11eb-8bda-a05cad16e92e.png">

**Comment by awwright** [comment]
I can't tell what's going on here by this alone, but you should be able to debug the error, look at the property that is failing, and then figure out what the value is and what it's supposed to be.

**Comment by awwright** [comment]
@hasansaghir The [validation result](https://github.com/tdegrunt/jsonschema#results) should include sufficient information to debug what's going on here. In particular, the `property` or `path` properties should tell you the particular instance that is failing.

If you have a particular suggestion on how the error reporting can be improved, please feel free to open a new issue.
