### ISSUE TITLE
Validation error "instance is not allowed to have the additional property "default"" when using "additionalProperties": false,

### ISSUE THREAD

**Issue by cnsdato** [tdegrunt/jsonschema#338]
When using the `"additionalProperties": false` on an object type the validator throw an error:
`instance is not allowed to have the additional property "default"`
How could this be prevented?

**Comment by tdegrunt** [comment]
This is not really the place to ask questions - ask them here instead: https://stackoverflow.com/questions/tagged/jsonschema
That being said: without seeing the instance this is hard to answer, but I'm guessing property default is not in your schema.
