### ISSUE TITLE
'propertyNames' does not exist in type 'Schema'

### ISSUE THREAD

**Issue by adrian-kriegel** [tdegrunt/jsonschema#340]
The type definition of `Schema` seems incomplete as `propertyNames` is missing. Does the library support `propertyNames`?

**Comment by awwright** [comment]
It should be landed as of 1.3.0.

Unfortunately I don't really know of any good way to test a TypeScript definition, so sometimes it gets missed.

**Comment by adrian-kriegel** [comment]
In theory, you could create a json-schema from the typescript definitions and compare it to the json-schema-schema, if that makes sense...

> Unfortunately I don't really know of any good way to test a TypeScript definition, so sometimes it gets missed.

**Comment by awwright** [comment]
Landed in 5e219db670bb8a57f5af932e21d51e2ccf44e679
