### ISSUE TITLE
Cannot find module 'url'

### ISSUE THREAD

**Issue by mamadfar** [tdegrunt/jsonschema#367]
After I deploy my project ( react => v17 ), when I try to move that page which I used jsonschema, I get this error
"Cannot find module 'url'".
For fixed this I had to install url package manually in the project.
But this is a temporary way.
Can you fix this ?

**Comment by xbw19975** [comment]
简直 bull shit，写代码不考虑不在node环境下的吗，如果说只能运行在node环境，请在文档里标名。

**Comment by geotom** [comment]
Same here: Had to add "url" to my packages, and then in the code where i use it I had to import as well before calling the validation (import * as url from "url"). Otherwise the validation throws an error that `urilib.resolve` is not a method

**Comment by gugurete** [comment]
Yes, tdegrunt/jsonschema has an implicit dependency on the "url" library.
It would be nice to make this explicit or even better ditch it altogether to have a nice, lean, no external dependencies jsonschema validator

**Comment by awwright** [comment]
The "url" package should be builtin. It is _not_ supposed to refer to a third-party package. Can you tell me a little more about your environment?

**Comment by smeng9** [comment]
Hi @awwright any updates on this issue?

**Comment by tdegrunt** [comment]
The above PR should address this issue.
