### ISSUE TITLE
Date as custom type

### ISSUE THREAD

**Issue by urdarinda** [tdegrunt/jsonschema#370]
Hi,
I wanted to understand why date is a type that is supported out of the box while the json spec does lists it only as a `format` to string. It should not be a types on its own

In [this](https://github.com/tdegrunt/jsonschema/issues/169), we also mention that date is not a type but a format

**Comment by urdarinda** [comment]
https://github.com/tdegrunt/jsonschema/blob/master/lib/validator.js#L325

**Comment by awwright** [comment]
This is a custom extension so that you can use this library with other kinds of data besides objects read from JSON. It's not a standard part of JSON Schema.
