### ISSUE TITLE
[DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.

### ISSUE THREAD

**Issue by runningrunning** [tdegrunt/jsonschema#393]
at urlParse (node:url:155:13)
    at Object.urlResolve [as resolve] (node:url:735:10)
    at Validator.validate (validator.js:118:21)

Both `resolve` and `parse` are marked as deprecated since Node v18.

**Comment by tdegrunt** [comment]
The above PR should address this issue.
