### ISSUE TITLE
Vite Module "url" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by kocynko** [tdegrunt/jsonschema#395]
` [plugin:vite:resolve] [plugin vite:resolve] Module "url" has been externalized for browser compatibility, imported by "C:/Users/matus.kocian/project/zurich_dashboards/test-nuxt/node_modules/jsonschema/lib/validator.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.`

I am facing this warning which probably cause error that it cannot find validate() function..

I am using nuxt 3.10.3 and vue 3.4.2

Any idea how to fix it ? Since i am rebuilding the code from nuxt v2 to nuxt v3 this is one of the issue that is holding me

**Comment by tdegrunt** [comment]
The above PR should address this issue.
