### ISSUE TITLE
Validation message i18n

### ISSUE THREAD

**Issue by rumkin** [tdegrunt/jsonschema#50]
I need to customize messages for translation. But  it [hardcoded into attributes](https://github.com/tdegrunt/jsonschema/blob/master/lib/attribute.js#L303). Is there any way to get attribute error code/id and values to put into validation message?

**Comment by martinib77** [comment]
+1

**Comment by mershal** [comment]
+1!

I've created an issue about this topic

**Comment by Acubed** [comment]
There's also #58
Unfortunately there's no option for a status code in most Error messages, though I suppose we could add one since we're using a custom ValidationError object. How's that sound?

**Comment by rumkin** [comment]
ValidationError is strict and proper. So it looks like a solution.

**Comment by mershal** [comment]
I think that a status and a property name / path would really help developers. Each validation message checks something different than the others, so it should be pretty simple. 
Thanks a lot!

**Comment by romeovs** [comment]
:+1:

**Comment by Acubed** [comment]
#123 was merged. It exposes "name" and "argument" properties on ValidationError objects so you can construct localized messages with the same content as the system error message.

Is there anything else that would be helpful?

**Comment by DimitryDushkin** [comment]
@rumkin issue can be closed?

**Comment by rumkin** [comment]
Yes

**Comment by awwright** [comment]
I'm closing this out because `ValidationError` should provide enough information to construct your own responses, see the `name` and `argument` properties. See also #212

If that is confusing at all, or if there's any additional features that can be added, please open a new issue.
