### ISSUE TITLE
Number validation accepts NaN

### ISSUE THREAD

**Issue by hazkiel** [tdegrunt/jsonschema#53]
When validating a number field, NaN shouldn't be accepted as a valid value but it currently is.

**Comment by offero** [comment]
This also bit me. NaN should fail validation, but it does not.

**Comment by offero** [comment]
https://github.com/tdegrunt/jsonschema/pull/152

**Comment by Acubed** [comment]
@offero Can you provide an example of how?

This shouldn't generally be a problem if you're using JSON.parse() since that's guaranteed to not produce NaN.

That being said, it can produce +-Infinity if you provide it a (perfectly legal) very large number:

    JSON.parse('999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999') == Number.POSITIVE_INFINITY

What should we do about this case?

**Comment by offero** [comment]
I made a PR for it.

Interesting case. I would not expect it to do so because it's not in the JSON spec. I would think that's an issue with the parse function.

**Comment by offero** [comment]
In the case that the number is too big to represent as a 64-bit floating point value, what should JSON.parse do? I guess the authors thought it would be best to not error at that point.

**Comment by offero** [comment]
It's actually the parseFloat implementation.

From MDN:
    
    parseFloat can also parse and return the value Infinity. You can use the isFinite function to determine if the result is a finite number (not Infinity, -Infinity, or NaN).

```
> parseFloat('99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999')
Infinity
```

Python loads it fine:
``` 
In [1]: import json
In [2]: json.loads('99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999')
Out[2]: 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999L
```

**Comment by Acubed** [comment]
@offero But what's the problem you are facing, exactly?

The problem that this issue poses is that JSON allows arbitrary precision and prohibits NaN and +- Infinity, and that this isn't exactly compatible with how ECMAScript stores numbers.

If you're getting a true JSON document, you will never run into this issue, since JSON.parse does not produce `NaN`.

And we do wish to support implementations that wish to use a superset of JSON values -- allow schemas to specifying if `NaN` and `Infinity`, etc, is legal or not.

There's a lot of cases to account for, really.

**Comment by offero** [comment]
My problem is javascript object validation. If you call validate on an object with a NaN or Infinity number value, it will validate without errors. I am preventing invalid objects from being processed by my library by validating them.

I agree that I would simply like to specify that NaN or +- Infinity is not allowed. That would be great, but no where in the JSON schema spec does it allow for those restrictions.

**Comment by tdegrunt** [comment]
Hmm, I did merge https://github.com/tdegrunt/jsonschema/commit/7360a235edec38545498b36459bb3d494fa5551b 

JSON schema doesn't allow for these restrictions indeed, so after some consideration I'm inclined to take it out. Thoughts?

**Comment by offero** [comment]
The questions are: Should validate() pass with an object with NaN or +-Infinity values? Should validate() allow values that are not specified in the JSON spec (NaN and +-Infinity are not specified)?

The major problem here is with the JSON parsing. As pointed out above with the number converting to Infinity, there is a difference between validating the JSON text and validating the parsed object.

**Comment by awwright** [comment]
Ok, re-looking at this now.

NaN isn't a legal JSON value, so on next major version release, how about a configurable option on how to handle it:

* number - treat as a number (current behavior)
* invalid - always invalid
* null - treat same as `null` (which is what JSON.stringify converts NaN to)
* undefined - treat same as undefined
* other value - e.g. treat as zero

**Comment by awwright** [comment]
It looks like NaN no longer validates as a number, I'll open a new issue to deal with configuring the behavior.
