### ISSUE TITLE
Method to coerce instance into validation

### ISSUE THREAD

**Issue by awwright** [tdegrunt/jsonschema#81]
A useful feature for many applications would be a function that takes a possibly non-validating instance, and "coerces" it into validation. Strings would be parsed into integers, if the property is specified as an integer; values would be placed into arrays, if the property is specified as an array; missing properties would be given their default values; and so on.

There's many possible use cases for this:

In a software that stores instances of schemas, when a user creates a new instance of a schema, I would like them to be presented with a "minimally validating instance" for example purposes.

Similarly, when a user stores a schema, perhaps make trivial corrections instead of sending back a parse error.

When a URL encoded string from HTML forms, or the proposed enctype="application/json" value for HTML forms, is sent, it's received only as strings. JSON Schema could be used to convert the strings back to the native, correct type.

For me, this is also the case with reverse-parsing URI Templates. I can generate URIs of form http://example.com/uid/{uid} where `id` is an integer, but if I parse a URI like http://example.com/uid/4, the `4` must be converted to an integer before I can query the database. Coercing the object `{"uid":"4"}` to the schema `{"properties":{"uid":{"type":"string"}}}` would eliminate the need to do this explicitly.

This seems like an in-scope feature, as it would be most useful as a method on the existing prototype, but super programmer senses tell me this is better done as a separate project/module.

Feedback welcome.

**Comment by KyleCartmell** [comment]
I'd like to have this feature. I agree that an hook or module would probably be best.

What needs to happen to get #68, or something like it, merged? Seems like there was a CI failure but not necessarily related to the changes in the PR.

**Comment by Acubed** [comment]
Hmm, I'll have to take a closer look at it.

If I recall, validity/type coercion was an idea that we sort of thought would be kind of out of scope, but another library could use a lot of the functionality from this one.

**Comment by KyleCartmell** [comment]
I really like the DRYness of being able to specify types in one place and the efficiency of doing the validation and coercion of in a single traversal. I think there might also be some other interesting applications of hooks within jsonschema that allow users to avoid having to duplicate (poorly, most likely) some aspect(s) of the schema/data traversal. To this end, I'd be very interested in taking part in a conversation on this topic if there's any appetite for it and I'd be happy to contribute some development effort towards it as well.

**Comment by webarthur** [comment]
I need some method like this too. The AJV has coercion just by using `var ajv = new Ajv({ coerceTypes: true })`... there is some module to add coerce types to jsonschema? Or some complete function that can do it?

Btw, the example in the README is missing the top of the function code.

**Comment by webarthur** [comment]
Guys, the example code in the README seems to be WRONG! There is no "this.attributes" even with `.bind(validator)`, it is always a empty object `{}`.

**Comment by awwright** [comment]
@webarthur I'm not quite sure what you're trying to do, exactly, can you please open a new issue about the README?

**Comment by webarthur** [comment]
@awwright "Method to coerce instance into validation"... that's just it. Coerce types in AJV module: https://github.com/epoberezkin/ajv#coercing-data-types

I just need a good function to coerce types. I have researching but I found nothing for jsonschema module.

**Comment by awwright** [comment]
I'm going to close this because it's out of scope. Performing this is surprisingly complicated and better suited as a separate library. Feel free to link to those here.
