### ISSUE TITLE
subSchemas

### ISSUE THREAD

**Issue by PauloASilva** [tdegrunt/jsonschema#89]
Hi,
I was testing how to describe a required JSON property which is a subSchema.
I was expecting something like

    var subSchema = {
        "id": "/subSchema",
        "type": "object",
        "properties": {
            "prop1": { "type": "string", "required": true },
            "prop2": { "type": "string", "required": true }
        }
    };

    var schema = {
        "id": "/schema",
        "type": "object",
        "properties": {
            "prop1": { "$ref": "/subSchema", "required": true },
            "prop2": { "type": "string", "required": true }
        }
    };

This way I can reuse the subScheme on another schema where the property is not required, although it seems that jsonschema expects the "required" options on subSchema itself.

    var subSchema = {
        "id": "/subSchema",
        "type": "object",
       "required": true,
        "properties": {
            "prop1": { "type": "string", "required": true },
            "prop2": { "type": "string", "required": true }
        }
    };

    var schema = {
        "id": "/schema",
        "type": "object",
        "properties": {
            "prop1": { "$ref": "/subSchema"},
            "prop2": { "type": "string", "required": true }
        }
    };

Can you clarify the `required` feature?
Thanks,
Paulo A. Silva

**Comment by Prestaul** [comment]
I don't think that `required:true` on a property is a defined feature of json schema... The `required: []` array of required properties is and works fine with this library today although both seem to work under some circumstances.

**Comment by PauloASilva** [comment]
@Prestaul I do agree. I don't know how I didn't notice the `required: []` at first glance.

**Comment by Prestaul** [comment]
@PauloASilva, you were right that this library seems to support `required:true` in some circumstances and it is demonstrated in the example in the readme. @tdegrunt, would it be wise to not feature this feature in the readme?

**Comment by Acubed** [comment]
`required:true` is how JSON Schema draft-3 was defined, so it's allowed in the library for historical reasons.

In the next draft, we'll likely be abandoning the keyword altogether and getting "requiredProperties" in addition to the list of optional "properties".

**Comment by Acubed** [comment]
@PauloASilva Does #100 I merged from @Prestaul fix your issue? If so, feel free to close this. Thanks!

**Comment by PauloASilva** [comment]
Documentation update is enough to clarify how to deal with `required`. I'm closing this issue.
Thanks,
