### ISSUE TITLE
Add method to clean an object

### ISSUE THREAD

**Issue by Prestaul** [tdegrunt/jsonschema#99]
I need a mechanism to clean undeclared properties off of an object. I could use [another library](https://www.npmjs.com/package/json-schema-filter) or write my own function, but I'd rather have it as part of this library.

``` js
var cleaned = require('jsonschema').clean({
  name: 'Prestaul',
  foo: 'bar' // This should be removed
}, {
  type: 'object',
  properties: {
    name: { type:'string' }
  }
});

cleaned; // { name:'Prestaul' }
```

Even better, I would love to be able to validate and clean an object in a single pass. (syntax is up for debate)

``` js
var result = require('jsonschema').validateAndClean({
  name: 'Prestaul',
  foo: 'bar' // This should be removed
}, {
  type: 'object',
  properties: {
    name: { type:'string' }
  }
});
```

output:

``` js
{
  valid: true,
  errors: [], // empty if valid
  instance: {}, // the original object
  cleanInstance: {} // the cleaned object if valid, else null
}
```

Does this feel like something that belongs here? I'm happy to help contribute, but lack the familiarity with the project to feel comfortable jumping in without first ensuring my approach fits the intended design. Looking for feedback.

**Comment by awwright** [comment]
I don't think it should be in the scope of this package to transform instances. I think this would make more sense as a separate package.
